package com.sobrenaturaldirector.action;
public enum ActionAvailabilityStatus { AVAILABLE, UNAVAILABLE_MISSING_CAPABILITY, UNAVAILABLE_MISSING_PROVIDER, UNAVAILABLE_MISSING_CONTENT, UNAVAILABLE_DIMENSION, UNAVAILABLE_POLICY, UNAVAILABLE_CONTEXT, UNSUPPORTED }
