package com.sobrenaturaldirector.action;
public enum ActionType {
    NO_ACTION, SPAWN_ACTOR, DESPAWN_ACTOR, SPAWN_THREAT, DESPAWN_THREAT,
    PLACE_BLOCK, REMOVE_BLOCK, REPLACE_BLOCK, PLACE_STRUCTURE, ROLLBACK_STRUCTURE,
    CREATE_INVESTIGATION_SITE, CREATE_THREAT_PRESENCE, REGISTER_DISCOVERY,
    CREATE_HINT, ENTER_RECOVERY_WINDOW, AMBUSH, BOSS_ENCOUNTER,
    MOVE_ENTITY, SET_BEHAVIOR, ASSIGN_TARGET, GIVE_ITEM, EQUIP_ENTITY, DIMENSION_TRAVEL
}
