package com.sobrenaturaldirector.action;
public enum ActionExecutionStatus { NEW, RUNNING, COMPENSATING, NO_COMPENSATION_NEEDED, COMPENSATION_UNAVAILABLE, COMPLETED, PARTIAL, COMPENSATED, ABORTED, SAFETY_REJECTED, STALE, BUDGET_REJECTED, PROVIDER_UNAVAILABLE, FAILED, FAILED_COMPENSATION, PLAN_ONLY }
