package com.sobrenaturaldirector.action;

import java.security.MessageDigest;import java.nio.charset.Charset;import java.util.*;
import com.sobrenaturaldirector.capability.CapabilityQuery;
import com.sobrenaturaldirector.content.catalog.SemanticCatalog;
import com.sobrenaturaldirector.content.model.*;
import com.sobrenaturaldirector.decision.model.*;
import com.sobrenaturaldirector.provider.DirectorProviderRegistry;
import com.sobrenaturaldirector.situation.SituationContext;

/** One deterministic definition catalog shared by narrative and decisions. */
public final class SemanticActionCatalog {
    public static final String VERSION="semantic-action-stack-v1";
    public static final String POLICY_FINGERPRINT="action-policy-safe-default-v1";
    private final Map<String,ActionDefinition> definitions;
    public SemanticActionCatalog(Collection<ActionDefinition> values){TreeMap<String,ActionDefinition> r=new TreeMap<String,ActionDefinition>();if(values!=null)for(ActionDefinition d:values)if(r.put(d.getId(),d)!=null)throw new IllegalArgumentException("duplicate action definition");definitions=Collections.unmodifiableMap(r);}
    public static SemanticActionCatalog standard(){List<ActionDefinition> a=new ArrayList<ActionDefinition>();
        a.add(def("NO_ACTION",ActionType.NO_ACTION,ActionFamily.RECOVERY,ActionKind.PRIMITIVE,true,null,null,ActionTargetScope.NONE,ActionRollbackPolicy.NO_ROLLBACK_REQUIRED,ActionSafety.NON_DESTRUCTIVE,"", ""));
        a.add(def("SPAWN_ACTOR",ActionType.SPAWN_ACTOR,ActionFamily.ENTITY,ActionKind.PRIMITIVE,true,Arrays.asList(new SemanticCapability("director:actor_source"),new SemanticCapability("director:entity_lifecycle_control")),Collections.singleton(ContentKind.ENTITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.COMPENSATION_ONLY,ActionSafety.SPAWN,"customnpcs lifecycle",""));
        a.add(def("DESPAWN_ACTOR",ActionType.DESPAWN_ACTOR,ActionFamily.ENTITY,ActionKind.PRIMITIVE,true,Arrays.asList(new SemanticCapability("director:actor_source"),new SemanticCapability("director:entity_lifecycle_control")),Collections.singleton(ContentKind.ENTITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.NO_ROLLBACK_REQUIRED,ActionSafety.SPAWN,"customnpcs lifecycle",""));
        a.add(def("SPAWN_THREAT",ActionType.SPAWN_THREAT,ActionFamily.THREAT,ActionKind.PRIMITIVE,true,Arrays.asList(new SemanticCapability("director:threat_source"),new SemanticCapability("director:entity_lifecycle_control")),Collections.singleton(ContentKind.ENTITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.COMPENSATION_ONLY,ActionSafety.SPAWN,"slenderman lifecycle",""));
        a.add(def("DESPAWN_THREAT",ActionType.DESPAWN_THREAT,ActionFamily.THREAT,ActionKind.PRIMITIVE,true,Arrays.asList(new SemanticCapability("director:threat_source"),new SemanticCapability("director:entity_lifecycle_control")),Collections.singleton(ContentKind.ENTITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.NO_ROLLBACK_REQUIRED,ActionSafety.SPAWN,"slenderman lifecycle",""));
        a.add(def("PLACE_STRUCTURE",ActionType.PLACE_STRUCTURE,ActionFamily.WORLD,ActionKind.PRIMITIVE,true,Arrays.asList(new SemanticCapability("director:structure_source"),new SemanticCapability("director:block_mutation")),Collections.singleton(ContentKind.STRUCTURE_CAPABILITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.ROLLBACK_REQUIRED,ActionSafety.MUTATION,"gravestone composition",""));
        a.add(def("ROLLBACK_STRUCTURE",ActionType.ROLLBACK_STRUCTURE,ActionFamily.WORLD,ActionKind.PRIMITIVE,true,Collections.singleton(new SemanticCapability("director:rollback_safe")),Collections.singleton(ContentKind.STRUCTURE_CAPABILITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.NO_ROLLBACK_REQUIRED,ActionSafety.MUTATION,"gravestone rollback",""));
        a.add(def("CREATE_INVESTIGATION_SITE",ActionType.CREATE_INVESTIGATION_SITE,ActionFamily.INVESTIGATION,ActionKind.COMPOSITE,false,Arrays.asList(new SemanticCapability("director:structure_source"),new SemanticCapability("director:actor_source")),Arrays.asList(ContentKind.STRUCTURE_CAPABILITY,ContentKind.ENTITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.COMPENSATION_ONLY,ActionSafety.MUTATION,"structure + actor composition","requires composed plan"));
        a.add(def("CREATE_THREAT_PRESENCE",ActionType.CREATE_THREAT_PRESENCE,ActionFamily.THREAT,ActionKind.COMPOSITE,false,Arrays.asList(new SemanticCapability("director:threat_source"),new SemanticCapability("director:entity_lifecycle_control")),Collections.singleton(ContentKind.ENTITY),ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.COMPENSATION_ONLY,ActionSafety.SPAWN,"threat lifecycle composition","requires composed plan"));
        a.add(def("AMBUSH",ActionType.AMBUSH,ActionFamily.THREAT,ActionKind.COMPOSITE,false,null,null,ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.COMPENSATION_ONLY,ActionSafety.MAJOR,"","missing behavior/target controls"));
        a.add(def("BOSS_ENCOUNTER",ActionType.BOSS_ENCOUNTER,ActionFamily.THREAT,ActionKind.COMPOSITE,false,null,null,ActionTargetScope.EXPLICIT_DIMENSION,ActionRollbackPolicy.COMPENSATION_ONLY,ActionSafety.MAJOR,"","missing behavior/target/attribute controls"));
        return new SemanticActionCatalog(a);
    }
    private static ActionDefinition def(String id,ActionType t,ActionFamily f,ActionKind k,boolean e,Collection<SemanticCapability> c,Collection<ContentKind> d,ActionTargetScope s,ActionRollbackPolicy r,ActionSafety risk,String path,String reason){return new ActionDefinition(id,t,f,k,e,c,d,s,r,risk,Collections.<String,Double>emptyMap(),path,reason);}
    public Map<String,ActionDefinition> getDefinitions(){return definitions;}public ActionDefinition get(String id){return definitions.get(id);}public int size(){return definitions.size();}
    public List<ActionDefinition> available(DecisionContext context,SituationContext situation,DirectorProviderRegistry registry,SemanticCatalog content){List<ActionDefinition> result=new ArrayList<ActionDefinition>();for(ActionDefinition d:definitions.values())if(availability(d.getId(),context,situation,registry,content).isAvailable())result.add(d);return Collections.unmodifiableList(result);}
    public Map<String,ActionAvailability> unavailable(DecisionContext context,SituationContext situation,DirectorProviderRegistry registry,SemanticCatalog content){Map<String,ActionAvailability> result=new LinkedHashMap<String,ActionAvailability>();for(ActionDefinition d:definitions.values()){ActionAvailability a=availability(d.getId(),context,situation,registry,content);if(!a.isAvailable())result.put(d.getId(),a);}return Collections.unmodifiableMap(result);}
    public ActionAvailability availability(String id,DecisionContext context,SituationContext situation,DirectorProviderRegistry registry,SemanticCatalog content){ActionDefinition d=get(id);if(d==null)return new ActionAvailability(ActionAvailabilityStatus.UNAVAILABLE_CONTEXT,"unknown action");if(!d.isExecutable())return new ActionAvailability(ActionAvailabilityStatus.UNSUPPORTED,d.getUnavailableReason());if(context==null||registry==null)return new ActionAvailability(ActionAvailabilityStatus.UNAVAILABLE_CONTEXT,"context or registry missing");if(d.getDimensionScope()!=ActionTargetScope.NONE&&(context.getCurrentDimension()==null&&situation==null))return new ActionAvailability(ActionAvailabilityStatus.UNAVAILABLE_DIMENSION,"explicit dimension context required");for(SemanticCapability c:d.getCapabilities())if(registry.query(new CapabilityQuery(c)).isEmpty())return new ActionAvailability(ActionAvailabilityStatus.UNAVAILABLE_MISSING_CAPABILITY,c.getValue());if(content!=null&&!d.getContentKinds().isEmpty()){boolean found=false;for(SemanticContentEntry e:content.getEntries().values())if(d.getContentKinds().contains(e.getKind())&&registry.get(e.getProvider())!=null)found=true;if(!found)return new ActionAvailability(ActionAvailabilityStatus.UNAVAILABLE_MISSING_CONTENT,"no registry-backed content");}return new ActionAvailability(ActionAvailabilityStatus.AVAILABLE,"requirements resolved");}
    public String fingerprint(){try{MessageDigest d=MessageDigest.getInstance("SHA-256");for(ActionDefinition x:definitions.values())d.update((x.getId()+"|"+x.fingerprint()+"\n").getBytes(Charset.forName("UTF-8")));byte[] b=d.digest();StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format(Locale.ENGLISH,"%02x",v&255));return x.toString();}catch(Exception e){throw new IllegalStateException(e);}}
}
