package com.sobrenaturaldirector.planner.model;
public enum PlanStepType { SELECT_LOCATION, VALIDATE_LOCATION, REQUEST_REGION_RESERVATION, PREPARE_STRUCTURE, PREPARE_CONTENT, PREPARE_ENCOUNTER, PREPARE_BOSS, PREPARE_REWARD, HIDE, WAIT_FOR_REVEAL, REVEAL, ACTIVATE, CLEANUP }
