package com.sobrenaturaldirector.situation;

import java.util.*;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import com.sobrenaturaldirector.action.*;
import com.sobrenaturaldirector.control.DimensionRef;

/** Bounded WorldSavedData DTO. It contains no live world/provider/entity object. */
public final class PersistentSituation {
    public static final int SITUATION_PERSISTENCE_SCHEMA_VERSION=1, SCHEMA_VERSION=SITUATION_PERSISTENCE_SCHEMA_VERSION, MAX_RECORDS=64;
    private final SituationInstance instance;
    public PersistentSituation(SituationInstance instance){if(instance==null)throw new IllegalArgumentException("situation required");this.instance=instance;}
    public SituationInstance getInstance(){return instance;}
    public String getId(){return instance.getId();}
    public NBTTagCompound toNbt(){
        SituationInstance s=instance; NBTTagCompound n=new NBTTagCompound(); n.setInteger("schemaVersion",SCHEMA_VERSION);
        n.setString("id",s.getId()); n.setString("goal",s.getGoal().name()); n.setString("threadId",s.getThreadId());
        n.setString("contextFingerprint",s.getContextFingerprint()); n.setString("providerFingerprint",s.getProviderFingerprint()); n.setString("contentFingerprint",s.getContentFingerprint());
        n.setLong("creationTick",s.getCreationTick()); n.setLong("lastTransitionTick",s.getLastTransitionTick()); n.setString("state",s.getState().name());
        writeDimension(n,"origin",s.getOriginDimension()); writeDimension(n,"relevant",s.getRelevantDimension()); writeBlueprint(n,s.getBlueprint()); writePlan(n,s.getActionPlan());
        if(s.getOutcome()!=null){NBTTagCompound o=new NBTTagCompound();o.setString("planId",s.getOutcome().getPlanId());o.setString("status",s.getOutcome().getStatus().name());o.setInteger("completed",s.getOutcome().getCompletedSteps());o.setInteger("failed",s.getOutcome().getFailedSteps());o.setInteger("compensated",s.getOutcome().getCompensatedSteps());o.setString("reason",s.getOutcome().getReason());n.setTag("outcome",o);}
        NBTTagList ts=new NBTTagList();for(SituationLifecycleTransition t:s.getTransitions()){NBTTagCompound x=new NBTTagCompound();x.setString("from",t.getFrom().name());x.setString("to",t.getTo().name());x.setString("reason",t.getReason());x.setString("trigger",t.getTrigger());x.setLong("tick",t.getTick());ts.appendTag(x);}n.setTag("transitions",ts);return n;
    }
    public static PersistentSituation fromNbt(NBTTagCompound n){
        if(n==null||n.getInteger("schemaVersion")!=SCHEMA_VERSION)throw new IllegalArgumentException("unsupported situation schema");
        SituationBlueprint b=readBlueprint(n);ActionPlan p=readPlan(n);ActionOutcome o=null;if(n.hasKey("outcome",10)){NBTTagCompound x=n.getCompoundTag("outcome");o=new ActionOutcome(x.getString("planId"),ActionExecutionStatus.valueOf(x.getString("status")),x.getInteger("completed"),x.getInteger("failed"),x.getInteger("compensated"),x.getString("reason"));}
        List<SituationLifecycleTransition> ts=new ArrayList<SituationLifecycleTransition>();NBTTagList list=n.getTagList("transitions",10);if(list.tagCount()>128)throw new IllegalArgumentException("transition limit");for(int i=0;i<list.tagCount();i++){NBTTagCompound x=list.getCompoundTagAt(i);ts.add(new SituationLifecycleTransition(SituationLifecycleState.valueOf(x.getString("from")),SituationLifecycleState.valueOf(x.getString("to")),x.getString("reason"),x.getLong("tick"),x.getString("trigger")));}
        return new PersistentSituation(SituationInstance.restore(n.getString("id"),SituationGoal.valueOf(n.getString("goal")),b,n.getString("threadId"),readDimension(n,"origin"),readDimension(n,"relevant"),n.getString("contextFingerprint"),n.getString("providerFingerprint"),n.getString("contentFingerprint"),p,SituationLifecycleState.valueOf(n.getString("state")),n.getLong("creationTick"),n.getLong("lastTransitionTick"),o,ts));
    }
    private static void writeDimension(NBTTagCompound n,String key,DimensionRef d){NBTTagCompound x=new NBTTagCompound();x.setInteger("id",d.getDimensionId());x.setString("provider",d.getProviderIdentity());x.setBoolean("available",d.isAvailable());NBTTagList tags=new NBTTagList();for(String tag:d.getTags()){NBTTagCompound t=new NBTTagCompound();t.setString("value",tag);tags.appendTag(t);}x.setTag("tags",tags);n.setTag(key,x);}
    private static DimensionRef readDimension(NBTTagCompound n,String key){NBTTagCompound x=n.getCompoundTag(key);NBTTagList l=x.getTagList("tags",10);List<String> tags=new ArrayList<String>();for(int i=0;i<l.tagCount();i++)tags.add(l.getCompoundTagAt(i).getString("value"));return new DimensionRef(x.getInteger("id"),x.getString("provider"),tags,x.getBoolean("available"));}
    private static void writeBlueprint(NBTTagCompound n,SituationBlueprint b){NBTTagCompound x=new NBTTagCompound();x.setString("id",b.getId());x.setString("goal",b.getGoal().name());x.setString("intensity",b.getIntensity().name());x.setInteger("baseScore",b.getBaseScore());x.setInteger("risk",b.getRisk());writeRoles(x,"required",b.getRequiredRoles());writeRoles(x,"optional",b.getOptionalRoles());n.setTag("blueprint",x);}
    private static SituationBlueprint readBlueprint(NBTTagCompound n){NBTTagCompound x=n.getCompoundTag("blueprint");return new SituationBlueprint(x.getString("id"),SituationGoal.valueOf(x.getString("goal")),readRoles(x,"required"),readRoles(x,"optional"),SituationIntensity.valueOf(x.getString("intensity")),x.getInteger("baseScore"),x.getInteger("risk"));}
    private static void writeRoles(NBTTagCompound n,String key,List<SemanticRole> roles){NBTTagList l=new NBTTagList();for(SemanticRole r:roles){NBTTagCompound x=new NBTTagCompound();x.setString("value",r.name());l.appendTag(x);}n.setTag(key,l);}
    private static List<SemanticRole> readRoles(NBTTagCompound n,String key){NBTTagList l=n.getTagList(key,10);List<SemanticRole> out=new ArrayList<SemanticRole>();for(int i=0;i<l.tagCount();i++)out.add(SemanticRole.valueOf(l.getCompoundTagAt(i).getString("value")));return out;}
    private static void writePlan(NBTTagCompound n,ActionPlan p){NBTTagCompound x=new NBTTagCompound();x.setString("id",p.getPlanId());x.setString("dimensionProvider",p.getDimension().getProviderIdentity());x.setInteger("dimensionId",p.getDimension().getDimensionId());x.setBoolean("dimensionAvailable",p.getDimension().isAvailable());NBTTagList dimensionTags=new NBTTagList();for(String tag:p.getDimension().getTags()){NBTTagCompound t=new NBTTagCompound();t.setString("value",tag);dimensionTags.appendTag(t);}x.setTag("dimensionTags",dimensionTags);NBTTagList nodes=new NBTTagList();for(ActionPlanNode a:p.getNodes()){NBTTagCompound y=new NBTTagCompound();y.setString("id",a.getNodeId());y.setString("action",a.getActionId());y.setBoolean("optional",a.isOptional());y.setString("failure",a.getFailurePolicy());NBTTagList deps=new NBTTagList();for(String d:a.getDependencies()){NBTTagCompound z=new NBTTagCompound();z.setString("value",d);deps.appendTag(z);}y.setTag("dependencies",deps);nodes.appendTag(y);}x.setTag("nodes",nodes);n.setTag("actionPlan",x);}
    private static ActionPlan readPlan(NBTTagCompound n){NBTTagCompound x=n.getCompoundTag("actionPlan");List<ActionPlanNode> nodes=new ArrayList<ActionPlanNode>();NBTTagList l=x.getTagList("nodes",10);for(int i=0;i<l.tagCount();i++){NBTTagCompound y=l.getCompoundTagAt(i);NBTTagList d=y.getTagList("dependencies",10);List<String> deps=new ArrayList<String>();for(int j=0;j<d.tagCount();j++)deps.add(d.getCompoundTagAt(j).getString("value"));nodes.add(new ActionPlanNode(y.getString("id"),y.getString("action"),deps,y.getBoolean("optional"),y.getString("failure")));}NBTTagList tagsN=x.getTagList("dimensionTags",10);List<String> tags=new ArrayList<String>();for(int i=0;i<tagsN.tagCount();i++)tags.add(tagsN.getCompoundTagAt(i).getString("value"));return new ActionPlan(x.getString("id"),new DimensionRef(x.getInteger("dimensionId"),x.getString("dimensionProvider"),tags,x.getBoolean("dimensionAvailable")),nodes);}
}
