package com.sobrenaturaldirector.shadow;

import java.io.*;
import java.nio.charset.Charset;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

/** V2 append-only writer. V1 files are never opened by this class. */
public final class JsonlShadowV2EventWriter implements ShadowEventSink {
    public static final String SCHEMA="DIRECTOR_SHADOW_EXPERIENCE_V2";
    private ShadowObservationMetrics observationMetrics;
    private final AtomicLong writerErrors=new AtomicLong();
    private final File sessionRoot,eventsFile; private final ShadowRuntimeIdentity identity; private final String collectionId; private final AtomicLong sequence=new AtomicLong(); private BufferedWriter out; private boolean ended;
    public JsonlShadowV2EventWriter(File root,ShadowRuntimeIdentity id){if(root==null||id==null)throw new IllegalArgumentException("identity required");identity=id;collectionId="cs_"+token();sessionRoot=new File(new File(root,"v2/collection-sessions"),collectionId);if(!sessionRoot.mkdirs()&&!sessionRoot.isDirectory())throw new IllegalStateException("cannot create V2 session");eventsFile=new File(sessionRoot,"events-00000.jsonl");try{out=new BufferedWriter(new FileWriter(eventsFile));writeManifest("manifest-start.json",true);emit("COLLECTION_SESSION_START",0,common()+",\"collectionMode\":\"FIELD\",\"runtimeEnvironment\":\"DEDICATED_SERVER\",\"minecraftVersion\":\"1.7.10\",\"forgeVersion\":\"10.13.4.1614\"");}catch(IOException e){throw new IllegalStateException("V2 writer start failure",e);}}
    public synchronized String getCollectionSessionId(){return collectionId;}
    public synchronized void participantStart(String ps,String opaque,long tick){emit("PARTICIPANT_SESSION_START",tick,common()+",\"participantSessionId\":\""+esc(ps)+"\",\"opaqueParticipantId\":\""+esc(opaque)+"\",\"consentState\":\"ACCEPTED\",\"startReason\":\"CONSENT_ACCEPTED\"");}
    public synchronized void participantEnd(String ps,String opaque,String reason,long tick){emit("PARTICIPANT_SESSION_END",tick,common()+",\"participantSessionId\":\""+esc(ps)+"\",\"opaqueParticipantId\":\""+esc(opaque)+"\",\"endReason\":\""+esc(reason)+"\"");}
    public synchronized void executionStarted(String decision,String execution,long tick){emit("EXECUTION_STARTED",tick,common()+",\"decisionId\":\""+esc(decision)+"\",\"executionId\":\""+esc(execution)+"\"");}
    public synchronized void executionTerminal(String decision,String execution,String type,long tick,String reason){emit("EXECUTION_"+esc(type),tick,common()+",\"decisionId\":\""+esc(decision)+"\",\"executionId\":\""+esc(execution)+"\",\"reason\":\""+esc(reason)+"\"");}
    public synchronized void accept(ShadowScoreResult r){String d=esc(r.getSnapshot().getDecisionId());String suffix=",\"decisionId\":\""+d+"\",\"researchScope\":\"GLOBAL\",\"allActivePlayersConsented\":true";String diagnostic=r.getSnapshot().getDiagnostics()==null?"":","+r.getSnapshot().getDiagnostics().toJson();emit("DECISION_SNAPSHOT",r.getSnapshot().getTick(),common()+suffix+",\"featureSchema\":\""+esc(r.getSnapshot().getSchema())+"\",\"candidateCount\":"+r.getSnapshot().getCandidates().size()+diagnostic);emit("ACTUAL_DECISION",r.getSnapshot().getTick(),common()+suffix+",\"actualCandidateId\":\""+esc(r.getSnapshot().getHeuristicCandidateId())+"\""+diagnostic);StringBuilder scores=new StringBuilder("{");boolean first=true;for(Map.Entry<String,Double> e:r.getScores().entrySet()){if(!first)scores.append(',');first=false;scores.append('"').append(esc(e.getKey())).append("\":").append(e.getValue());}scores.append('}');emit("SHADOW_SCORE_RESULT",r.getSnapshot().getTick(),common()+suffix+",\"featureSchema\":\""+esc(r.getSnapshot().getSchema())+"\",\"shadowSelectedId\":\""+esc(r.getShadowSelectedId())+"\",\"latencyNanos\":"+r.getLatencyNanos()+",\"scores\":"+scores+diagnostic);if("candidate:no_action".equals(r.getSnapshot().getHeuristicCandidateId()))emit("DECISION_TERMINAL",r.getSnapshot().getTick(),common()+suffix+",\"terminalType\":\"NO_ACTION\",\"executionExpected\":false"+diagnostic);}
    public synchronized void bindMetrics(ShadowObservationMetrics metrics){observationMetrics=metrics;}
    public synchronized void healthSnapshot(ShadowObservationMetrics m,long tick){healthSnapshot(m,tick,0);}
    public synchronized void healthSnapshot(ShadowObservationMetrics m,long tick,long queueCurrent){emit("HEALTH_SNAPSHOT",tick,common()+",\"queueCurrent\":"+queueCurrent+",\"queueDrops\":"+m.getDropped()+",\"queueHighWatermark\":"+m.getHighWatermark()+",\"scorerRequests\":"+m.getRequests()+",\"scorerSuccess\":"+m.getScored()+",\"scorerErrors\":"+m.getErrors()+",\"writerEvents\":"+sequence.get()+",\"writerErrors\":"+writerErrors.get()+",\"writerRotationErrors\":0,\"outcomeTrackerTimeouts\":0,\"outcomeTrackerDrops\":0");}
    public synchronized void close(){if(ended)return;ended=true;String health=observationMetrics==null?",\"healthStatus\":\"UNKNOWN_NOT_EXPOSED\"":",\"healthStatus\":\"VALID\",\"queueDrops\":"+observationMetrics.getDropped()+",\"queueHighWatermark\":"+observationMetrics.getHighWatermark()+",\"scorerRequests\":"+observationMetrics.getRequests()+",\"scorerSuccess\":"+observationMetrics.getScored()+",\"scorerErrors\":"+observationMetrics.getErrors()+",\"writerEvents\":"+sequence.get()+",\"writerErrors\":"+writerErrors.get()+",\"writerRotationErrors\":0,\"modelRuntimeErrors\":"+observationMetrics.getErrors()+",\"outcomeTrackerTimeouts\":0,\"outcomeTrackerDrops\":0";emit("COLLECTION_SESSION_END",0,common()+",\"endReason\":\"SERVER_SHUTDOWN\""+health);try{out.close();writeManifest("manifest-end.json",false);}catch(IOException e){writerErrors.incrementAndGet();throw new IllegalStateException("V2 writer close failure",e);}}
    private String common(){return "\"schemaVersion\":\""+SCHEMA+"\",\"collectionSessionId\":\""+collectionId+"\",\"eventSequence\":"+(sequence.get()+1)+",\"trainingAllowed\":false,\"provenance\":{\"runtimeEnvironment\":\"DEDICATED_SERVER\",\"collectionMode\":\"FIELD\"},\"jarSha256\":\""+esc(identity.jarSha256)+"\",\"jarShaStatus\":\""+identity.jarShaStatus+"\",\"modelSha256\":\""+esc(identity.modelSha256)+"\",\"frozenConfigSha256\":\""+esc(identity.frozenConfigSha256)+"\",\"featureSchemaSha256\":\""+esc(identity.featureSchemaSha256)+"\"";}
    private void emit(String type,long tick,String body){try{long n=sequence.incrementAndGet();String line="{"+body.substring(0,body.length())+",\"eventType\":\""+type+"\",\"serverTick\":"+tick+"}";out.write(line);out.newLine();out.flush();}catch(IOException e){writerErrors.incrementAndGet();throw new IllegalStateException("V2 writer failure",e);}}
    private void writeManifest(String name,boolean start)throws IOException{File f=new File(sessionRoot,name);BufferedWriter w=new BufferedWriter(new FileWriter(f));w.write("{\"schemaVersion\":\""+SCHEMA+"\",\"collectionSessionId\":\""+collectionId+"\",\"manifestType\":\""+(start?"START":"END")+"\",\"jarSha256\":\""+esc(identity.jarSha256)+"\",\"jarShaStatus\":\""+identity.jarShaStatus+"\",\"modelSha256\":\""+esc(identity.modelSha256)+"\",\"frozenConfigSha256\":\""+esc(identity.frozenConfigSha256)+"\",\"featureSchemaSha256\":\""+esc(identity.featureSchemaSha256)+"\",\"trainingAllowed\":false,\"eventCount\":"+sequence.get()+"}");w.newLine();w.close();}
    private static String esc(String s){return s==null?"":s.replace("\\","\\\\").replace("\"","\\\"");}
    private static String token(){String a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";Random r=new Random();StringBuilder b=new StringBuilder(12);for(int i=0;i<12;i++)b.append(a.charAt(r.nextInt(a.length())));return b.toString();}
}
