package com.sobrenaturaldirector.shadow;

import java.util.*;

/** Immutable, bounded diagnostic summary; it cannot influence a decision. */
public final class ShadowDecisionDiagnostics {
    private final int candidateCount, actionCandidateCount, noActionCandidateCount, eligibleActionCandidateCount, rejectedCandidateCount, safetyRejectedCandidateCount, feasibilityRejectedCandidateCount, providerCandidateCount, availableProviderCount, missingProviderCount;
    private final String primaryReason;
    private final List<String> failedConstraintCodes;
    public ShadowDecisionDiagnostics(int total,int actions,int noActions,int eligibleActions,int rejected,int safetyRejected,int feasibilityRejected,int providers,int available,int missing,String reason,Collection<String> failures){
        if(total<0||actions<0||noActions<0||eligibleActions<0||rejected<0||safetyRejected<0||feasibilityRejected<0||providers<0||available<0||missing<0)throw new IllegalArgumentException("negative diagnostic count");
        candidateCount=total;actionCandidateCount=actions;noActionCandidateCount=noActions;eligibleActionCandidateCount=eligibleActions;rejectedCandidateCount=rejected;safetyRejectedCandidateCount=safetyRejected;feasibilityRejectedCandidateCount=feasibilityRejected;providerCandidateCount=providers;availableProviderCount=available;missingProviderCount=missing;primaryReason=reason==null?"UNKNOWN":reason;failedConstraintCodes=Collections.unmodifiableList(new ArrayList<String>(failures==null?Collections.<String>emptyList():failures));
    }
    public int getCandidateCount(){return candidateCount;} public int getActionCandidateCount(){return actionCandidateCount;} public int getNoActionCandidateCount(){return noActionCandidateCount;} public int getEligibleActionCandidateCount(){return eligibleActionCandidateCount;} public int getRejectedCandidateCount(){return rejectedCandidateCount;} public int getSafetyRejectedCandidateCount(){return safetyRejectedCandidateCount;} public int getFeasibilityRejectedCandidateCount(){return feasibilityRejectedCandidateCount;} public int getProviderCandidateCount(){return providerCandidateCount;} public int getAvailableProviderCount(){return availableProviderCount;} public int getMissingProviderCount(){return missingProviderCount;} public String getPrimaryReason(){return primaryReason;} public List<String> getFailedConstraintCodes(){return failedConstraintCodes;}
    public String toJson(){StringBuilder b=new StringBuilder("\"decisionDiagnostics\":{\"candidateCount\":").append(candidateCount).append(",\"actionCandidateCount\":").append(actionCandidateCount).append(",\"noActionCandidateCount\":").append(noActionCandidateCount).append(",\"noActionCandidatePresent\":").append(noActionCandidateCount>0).append(",\"eligibleActionCandidateCount\":").append(eligibleActionCandidateCount).append(",\"rejectedCandidateCount\":").append(rejectedCandidateCount).append(",\"safetyRejectedCandidateCount\":").append(safetyRejectedCandidateCount).append(",\"feasibilityRejectedCandidateCount\":").append(feasibilityRejectedCandidateCount).append(",\"providerCandidateCount\":").append(providerCandidateCount).append(",\"availableProviderCount\":").append(availableProviderCount).append(",\"missingProviderCount\":").append(missingProviderCount).append(",\"goalSatisfiable\":\"NOT_CAPTURED\",\"blueprintCandidateCount\":\"NOT_CAPTURED\",\"feasibleBlueprintCount\":\"NOT_CAPTURED\",\"requiredCapabilityCount\":\"NOT_CAPTURED\",\"missingCapabilityCount\":\"NOT_CAPTURED\",\"schedulerAllowed\":\"NOT_CAPTURED\",\"selectionReasonCode\":\"").append(esc(primaryReason)).append("\",\"failedConstraintCodes\":[");for(int i=0;i<failedConstraintCodes.size();i++){if(i>0)b.append(',');b.append('"').append(esc(failedConstraintCodes.get(i))).append('"');}return b.append("]}").toString();}
    private static String esc(String s){return s.replace("\\","\\\\").replace("\"","\\\"");}
}
