package com.sobrenaturaldirector.environment.model;

public enum EnvironmentSignal {
    LIGHT_SOURCE, STORAGE, CRAFTING, SMELTING, SLEEPING, FORTIFICATION,
    ACCESS_CONTROL, DECORATIVE_CONSTRUCTION, FARMING, UTILITY, REDSTONE,
    PLAYER_PRESENCE, PLAYER_MODIFICATION, VANILLA_VILLAGE, RECENT_ACTIVITY,
    DIRECTOR_OWNED_STRUCTURE
}
