package com.sobrenaturaldirector.runtimeprobe;

import java.util.*;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.gameevent.TickEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import net.minecraft.world.WorldServer;
import cpw.mods.fml.common.registry.GameData;
import com.sobrenaturaldirector.SobrenaturalDirector;
import com.sobrenaturaldirector.action.*;
import com.sobrenaturaldirector.composition.model.*;
import com.sobrenaturaldirector.control.*;
import com.sobrenaturaldirector.content.model.ProviderId;
import com.sobrenaturaldirector.persistence.*;

/** Disposable-only real provider chain probe. It never runs on the public server. */
@Mod(modid="sobrenaturaldirector_action_executor_probe", name="Director Action Executor Probe", version="ACTION-EXECUTOR-1")
public final class ActionExecutorClosureProbe {
    private boolean done;
    @Mod.EventHandler public void init(FMLInitializationEvent event){FMLCommonHandler.instance().bus().register(this);}
    @SubscribeEvent public void tick(TickEvent.ServerTickEvent event){
        if(event.phase!=TickEvent.Phase.END||done)return;
        WorldServer world=net.minecraftforge.common.DimensionManager.getWorld(0); if(world==null||SobrenaturalDirector.getActionPlanExecutor()==null)return;
        done=true; long tick=world.getTotalWorldTime(); DimensionRef dimension=new DimensionRef(world.provider.dimensionId,"runtime",Collections.singleton("e2e"),true); DirectorWorldSavedData saved=saved(world); for(Object key:GameData.getBlockRegistry().getKeys()) if(String.valueOf(key).toLowerCase().contains("gravestone")) log("BLOCK="+key);
        try { noAction(dimension,tick); primitiveActor(dimension,tick); primitiveThreat(dimension,tick); structureAndCompensation(dimension,tick,world,saved); compositeFailure(dimension,tick,world); contentStale(dimension,tick,world); staleProvider(dimension,tick); dimensionStale(dimension,tick); log("ACTION_EXECUTOR_E2E=PASS"); }
        catch(Throwable failure){log("ACTION_EXECUTOR_E2E=FAIL "+failure.getClass().getName()+" "+failure.getMessage());}
    }
    private void primitiveActor(DimensionRef d,long tick){
        ActionPlanExecutor executor=SobrenaturalDirector.getActionPlanExecutor(); SemanticActionCatalog catalog=SobrenaturalDirector.getActionCatalog();
        EntityRef entity=new EntityRef("e2e-actor",d,EntityOwnership.DIRECTOR_SPAWNED); WorldPositionRef pos=new WorldPositionRef(d,8,worldY(8,8),8); ControlLease lease=lease("actor",tick,2000);
        ActionPlan spawn=new ActionComposer().compose("e2e-actor-spawn",ActionType.SPAWN_ACTOR,d,catalog); ActionExecutionSpec spec=new ActionExecutionSpec(entity,pos,null,lease,ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-actor-mutation","E2E Witness");
        ActionOutcome result=executor.execute(spawn(Collections.singletonMap("action",spec),spawn),Collections.singletonMap("action",spec),context(d),tick); log("CUSTOMNPCS_PRIMITIVE="+result.getStatus()+" reason="+result.getReason()); require(result.getStatus()==ActionExecutionStatus.COMPLETED,"CustomNPC spawn");
        ActionPlan despawn=new ActionComposer().compose("e2e-actor-despawn",ActionType.DESPAWN_ACTOR,d,catalog); ActionOutcome cleanup=executor.execute(despawn,Collections.singletonMap("action",spec),context(d),tick+1); com.sobrenaturaldirector.mutation.runtime.MutationJournalEntry mutation=savedFor(d).getMutation("e2e-actor-mutation"); log("CUSTOMNPCS_CLEANUP="+cleanup.getStatus()+" control="+control(executor,"e2e-actor-despawn")+" journalStatus="+(mutation==null?"NONE":mutation.getStatus())); require(cleanup.getStatus()==ActionExecutionStatus.COMPLETED,"CustomNPC cleanup");
    }
    private void primitiveThreat(DimensionRef d,long tick){
        ActionPlanExecutor executor=SobrenaturalDirector.getActionPlanExecutor(); WorldServer world=net.minecraftforge.common.DimensionManager.getWorld(0); int sx=world.getSpawnPoint().posX, sz=world.getSpawnPoint().posZ; EntityRef entity=new EntityRef("e2e-threat",d,EntityOwnership.DIRECTOR_SPAWNED); WorldPositionRef pos=new WorldPositionRef(d,sx,worldY(sx,sz),sz); ActionExecutionSpec spec=new ActionExecutionSpec(entity,pos,null,lease("threat",tick,2000),ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-threat-mutation","E2E Threat");
        ActionPlan spawn=new ActionComposer().compose("e2e-threat-spawn",ActionType.SPAWN_THREAT,d,SobrenaturalDirector.getActionCatalog()); ActionOutcome threat=executor.execute(spawn,Collections.singletonMap("action",spec),context(d),tick+2); log("SLENDERMAN_PRIMITIVE="+threat.getStatus()+" reason="+threat.getReason()); require(threat.getStatus()==ActionExecutionStatus.COMPLETED,"SlenderMan spawn");
        ActionPlan despawn=new ActionComposer().compose("e2e-threat-despawn",ActionType.DESPAWN_THREAT,d,SobrenaturalDirector.getActionCatalog()); ActionOutcome cleanup=executor.execute(despawn,Collections.singletonMap("action",spec),context(d),tick+3); log("SLENDERMAN_CLEANUP="+cleanup.getStatus()+" control="+control(executor,"e2e-threat-despawn")); require(cleanup.getStatus()==ActionExecutionStatus.COMPLETED,"SlenderMan cleanup");
    }
    private void structureAndCompensation(DimensionRef d,long tick,WorldServer world,DirectorWorldSavedData saved){
        int x=12,z=12,y=world.getTopSolidOrLiquidBlock(x,z); ExternalBlockReference block=new ExternalBlockReference("GraveStone","GSBoneBlock",0); List<CompositionBlockOperation> ops=Collections.singletonList(new CompositionBlockOperation("e2e-block",0,0,0,block)); DirectorOwnedCompositionPlan composition=new DirectorOwnedCompositionPlan("e2e-composition","action-e2e","GraveStone","2.13.0",d.getDimensionId(),x,y,z,ops); ActionExecutionSpec spec=new ActionExecutionSpec(null,null,composition,lease("structure",tick,2000),ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-structure","E2E Structure");
        ActionPlan plan=new ActionComposer().compose("e2e-structure-apply",ActionType.PLACE_STRUCTURE,d,SobrenaturalDirector.getActionCatalog()); ActionOutcome applied=SobrenaturalDirector.getActionPlanExecutor().execute(plan,Collections.singletonMap("action",spec),context(d),tick+4); log("GRAVESTONE_APPLY="+applied.getStatus()+" reason="+applied.getReason()+" control="+control(SobrenaturalDirector.getActionPlanExecutor(),"e2e-structure-apply")); require(applied.getStatus()==ActionExecutionStatus.COMPLETED,"GraveStone apply");
        ActionPlan rollback=new ActionComposer().compose("e2e-structure-rollback",ActionType.ROLLBACK_STRUCTURE,d,SobrenaturalDirector.getActionCatalog()); ActionOutcome rolled=SobrenaturalDirector.getActionPlanExecutor().execute(rollback,Collections.singletonMap("action",spec),context(d),tick+5); log("GRAVESTONE_ROLLBACK="+rolled.getStatus()+" control="+control(SobrenaturalDirector.getActionPlanExecutor(),"e2e-structure-rollback")); require(rolled.getStatus()==ActionExecutionStatus.COMPLETED,"GraveStone rollback");
    }
    private void staleProvider(DimensionRef d,long tick){ActionPlan plan=new ActionComposer().compose("e2e-stale",ActionType.SPAWN_ACTOR,d,SobrenaturalDirector.getActionCatalog());EntityRef entity=new EntityRef("e2e-stale",d,EntityOwnership.DIRECTOR_SPAWNED);ActionExecutionSpec spec=new ActionExecutionSpec(entity,new WorldPositionRef(d,14,worldY(14,14),14),null,lease("stale",tick,2000),ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-stale","Stale");SobrenaturalDirector.getProviderRegistry().unregister(new ProviderId("customnpcs"));ActionOutcome stale=SobrenaturalDirector.getActionPlanExecutor().execute(plan,Collections.singletonMap("action",spec),context(d),tick+6);log("PROVIDER_UNREGISTER_STALE="+stale.getStatus());require(stale.getStatus()==ActionExecutionStatus.PROVIDER_UNAVAILABLE||stale.getStatus()==ActionExecutionStatus.STALE,"provider stale rejection");}
    private void noAction(DimensionRef d,long tick){ActionPlan plan=new ActionComposer().compose("e2e-no-action",ActionType.NO_ACTION,d,SobrenaturalDirector.getActionCatalog());ActionOutcome outcome=SobrenaturalDirector.getActionPlanExecutor().execute(plan,Collections.<String,ActionExecutionSpec>emptyMap(),context(d),tick);log("NO_ACTION="+outcome.getStatus());require(outcome.getStatus()==ActionExecutionStatus.COMPLETED,"no action");}
    private void dimensionStale(DimensionRef d,long tick){DimensionRef unavailable=new DimensionRef(d.getDimensionId(),"runtime",Collections.singleton("e2e"),false);ActionPlan plan=new ActionPlan("e2e-dimension-stale",unavailable,Collections.singletonList(new ActionPlanNode("action","NO_ACTION",Collections.<String>emptyList(),false,"ABORT")));ActionOutcome outcome=SobrenaturalDirector.getActionPlanExecutor().execute(plan,Collections.<String,ActionExecutionSpec>emptyMap(),context(d),tick+8);log("DIMENSION_STALE="+outcome.getStatus());require(outcome.getStatus()==ActionExecutionStatus.STALE,"dimension stale rejection");}
    private void contentStale(DimensionRef d,long tick,WorldServer world){int x=20,z=20,y=world.getTopSolidOrLiquidBlock(x,z);ExternalBlockReference missing=new ExternalBlockReference("GraveStone","GSRemovedDescriptor",0);DirectorOwnedCompositionPlan composition=new DirectorOwnedCompositionPlan("e2e-content-stale","action-e2e","GraveStone","2.13.0",d.getDimensionId(),x,y,z,Collections.singletonList(new CompositionBlockOperation("e2e-missing",0,0,0,missing)));ActionExecutionSpec spec=new ActionExecutionSpec(null,null,composition,lease("content",tick,2000),ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-content","Missing");ActionPlan plan=new ActionComposer().compose("e2e-content-stale-plan",ActionType.PLACE_STRUCTURE,d,SobrenaturalDirector.getActionCatalog());ActionOutcome outcome=SobrenaturalDirector.getActionPlanExecutor().execute(plan,Collections.singletonMap("action",spec),context(d),tick+8);log("CONTENT_REMOVAL_STALE="+outcome.getStatus());require(outcome.getStatus()==ActionExecutionStatus.FAILED,"content removal fail closed");}
    private void compositeFailure(DimensionRef d,long tick,WorldServer world){int x=16,z=16,y=world.getTopSolidOrLiquidBlock(x,z);ExternalBlockReference block=new ExternalBlockReference("GraveStone","GSBoneBlock",0);DirectorOwnedCompositionPlan composition=new DirectorOwnedCompositionPlan("e2e-comp-failure","action-e2e","GraveStone","2.13.0",d.getDimensionId(),x,y,z,Collections.singletonList(new CompositionBlockOperation("e2e-comp-block",0,0,0,block)));ActionPlanNode structure=new ActionPlanNode("structure","PLACE_STRUCTURE",Collections.<String>emptyList(),false,"COMPENSATE");ActionPlanNode actor=new ActionPlanNode("actor","SPAWN_ACTOR",Collections.singleton("structure"),false,"COMPENSATE");ActionPlan plan=new ActionPlan("e2e-composite-failure",d,Arrays.asList(structure,actor));ActionExecutionSpec worldSpec=new ActionExecutionSpec(null,null,composition,lease("comp-world",tick,2000),ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-comp-world","Comp");ActionExecutionSpec expiredActor=new ActionExecutionSpec(new EntityRef("e2e-comp-actor",d,EntityOwnership.DIRECTOR_SPAWNED),new WorldPositionRef(d,x,y,z),null,new ControlLease("lease-comp-actor","action-e2e",0,0,RestorationPolicy.RESTORABLE,true),ControlAuthority.FULL_DIRECTOR_CONTROL,"e2e-comp-actor","Comp Actor");Map<String,ActionExecutionSpec> specs=new LinkedHashMap<String,ActionExecutionSpec>();specs.put("structure",worldSpec);specs.put("actor",expiredActor);ActionOutcome outcome=SobrenaturalDirector.getActionPlanExecutor().execute(plan,specs,context(d),tick+7);log("COMPOSITE_FAILURE="+outcome.getStatus()+" compensated="+outcome.getCompensatedSteps());require(outcome.getStatus()==ActionExecutionStatus.COMPENSATED,"composite compensation");}
    private ActionPlan spawn(Map<String,ActionExecutionSpec> ignored,ActionPlan plan){return plan;}
    private ControlExecutionContext context(DimensionRef d){WorldServer world=net.minecraftforge.common.DimensionManager.getWorld(d.getDimensionId());return new ControlExecutionContext(world,saved(world));}
    private DirectorWorldSavedData saved(WorldServer world){DirectorWorldSavedData data=(DirectorWorldSavedData)world.perWorldStorage.loadData(DirectorWorldSavedData.class,DirectorPersistenceMetadata.DATA_NAME);if(data==null){data=new DirectorWorldSavedData(DirectorPersistenceMetadata.DATA_NAME);world.perWorldStorage.setData(DirectorPersistenceMetadata.DATA_NAME,data);}return data;}
    private DirectorWorldSavedData savedFor(DimensionRef d){return saved(net.minecraftforge.common.DimensionManager.getWorld(d.getDimensionId()));}
    private ControlLease lease(String id,long start,long span){return new ControlLease("lease-"+id,"action-e2e",Math.max(0,start-1),start+span,RestorationPolicy.RESTORABLE,true);}
    private int worldY(int x,int z){WorldServer world=net.minecraftforge.common.DimensionManager.getWorld(0);return world.getTopSolidOrLiquidBlock(x,z);}
    private String control(ActionPlanExecutor executor,String planId){ActionPlanJournal journal=executor.journal(planId);if(journal==null||journal.getEntries().isEmpty())return "NONE";ActionPlanJournal.Entry entry=journal.getEntries().values().iterator().next();return entry.getResult().name()+":"+entry.getReason();}
    private void require(boolean value,String message){if(!value)throw new IllegalStateException(message);}
    private void log(String value){System.out.println("[ACTION-EXECUTOR-PROBE] "+value);}
}
