package com.sobrenaturaldirector.decision.model;

public enum Intent {
    NO_ACTION, AMBIENT_HINT, HORROR_REVEAL, STALKING_PRESSURE, MINOR_ENCOUNTER,
    AMBUSH, LOOT_DISCOVERY, MYSTERY_SETUP, MYSTERY_PAYOFF, STRUCTURE_SEED,
    STRUCTURE_REVEAL, BOSS_SETUP, BOSS_ENCOUNTER, RECOVERY, ARC_TRANSITION
}
