package com.sobrenaturaldirector.spatial;

import java.util.*;import com.sobrenaturaldirector.composition.model.*;import com.sobrenaturaldirector.spatial.geometry.*;import com.sobrenaturaldirector.spatial.model.*;import com.sobrenaturaldirector.spatial.trace.SpatialPlanningTrace;import com.sobrenaturaldirector.spatial.validation.SpatialPlanValidator;

public final class AbstractSpatialPlanner {
 public SpatialPlanningResult plan(String requestId,StructureBlueprint blueprint,List<EncounterBlueprint> encounters,List<RewardBlueprint> rewards,SpatialBudget budget,long seed,boolean retroactive){List<String>events=new ArrayList<String>();if(blueprint==null){events.add("no_structure:anchors_deferred");return new SpatialPlanningResult(SpatialPlanningStatus.NO_SPATIAL_PLAN_REQUIRED,null,new SpatialPlanningTrace(requestId,"none",seed,0,0,events));}if(budget==null)return new SpatialPlanningResult(SpatialPlanningStatus.INVALID_INPUT,null,new SpatialPlanningTrace(requestId,blueprint.getId(),seed,0,0,Collections.singletonList("budget_missing")));if(blueprint.getNodes().size()>budget.getMaxNodes())return new SpatialPlanningResult(SpatialPlanningStatus.BUDGET_EXCEEDED,null,new SpatialPlanningTrace(requestId,blueprint.getId(),seed,0,0,Collections.singletonList("node_budget_exceeded")));
  List<SpatialNodePlacement> nodes=new ArrayList<SpatialNodePlacement>();Map<String,SpatialNodePlacement>bySource=new HashMap<String,SpatialNodePlacement>();int attempts=0;for(StructureNode n:blueprint.getNodes()){attempts++;int[] size=size(n.getType());int x=Math.multiplyExact(n.getPosition().getX(),16);int z=Math.multiplyExact(n.getPosition().getZ(),16);int y=Math.multiplyExact(n.getPosition().getY(),16);LocalVec3i origin=new LocalVec3i(x,y,z);LocalAabb volume=LocalAabb.sized(origin,size[0],size[1],size[2]);SpatialNodePlacement p=new SpatialNodePlacement(blueprint.getId()+":placement:"+n.getId(),n.getId(),volume,new LocalTransform(origin,LocalOrientation.NORTH,0),n.getPosition().getY(),n.isMandatory());nodes.add(p);bySource.put(n.getId(),p);events.add("placed:"+n.getId());}
  List<SpatialConnectorPlacement>connectors=new ArrayList<SpatialConnectorPlacement>();for(StructureConnector c:blueprint.getConnectors()){SpatialNodePlacement from=bySource.get(c.getFrom()),to=bySource.get(c.getTo());if(from==null||to==null){events.add("rejected_connector:"+c.getId());continue;}LocalAabb v=connector(from.getVolume(),to.getVolume());connectors.add(new SpatialConnectorPlacement(blueprint.getId()+":connector:"+c.getId(),c.getId(),from.getPlacementId(),to.getPlacementId(),v));}
  Map<String,LocalAnchor>anchors=new TreeMap<String,LocalAnchor>();if(!nodes.isEmpty()){SpatialNodePlacement entrance=nodes.get(0);anchors.put("entrance",anchor("entrance",entrance));for(EncounterBlueprint e:encounters==null?Collections.<EncounterBlueprint>emptyList():encounters){SpatialNodePlacement p=bySource.get(e.getNodeId());if(p==null)p=bySource.get("main");if(p!=null)anchors.put(e.getId(),anchor(e.getId(),p));}for(RewardBlueprint r:rewards==null?Collections.<RewardBlueprint>emptyList():rewards){SpatialNodePlacement p=bySource.get(r.getNodeId());if(p==null)p=bySource.get("reward");if(p!=null)anchors.put(r.getId(),anchor(r.getId(),p));}}
  LocalAabb bounds=null;long volume=0;for(SpatialNodePlacement p:nodes){bounds=bounds==null?p.getVolume():bounds.union(p.getVolume());volume=Math.addExact(volume,p.getVolume().volume());}for(SpatialConnectorPlacement c:connectors){bounds=bounds==null?c.getVolume():bounds.union(c.getVolume());volume=Math.addExact(volume,c.getVolume().volume());}if(bounds==null||bounds.getWidth()>budget.getMaxWidth()||bounds.getHeight()>budget.getMaxHeight()||bounds.getDepth()>budget.getMaxDepth()||volume>budget.getMaxVolume()){events.add("budget_exceeded:footprint");return new SpatialPlanningResult(SpatialPlanningStatus.BUDGET_EXCEEDED,null,new SpatialPlanningTrace(requestId,blueprint.getId(),seed,attempts,nodes.size(),events));}List<String>requirements=new ArrayList<String>(Arrays.asList("SUFFICIENT_FOOTPRINT","AVOID_PLAYER_BUILD","RUNTIME_SITE_VALIDATION_REQUIRED"));if(retroactive)requirements.add("UNOBSERVED_FOR_RETROACTIVE_MUTATION");if(bounds.getMin().getY()<0)requirements.add("ALLOW_VERTICAL_DESCENT");SpatialFootprint footprint=new SpatialFootprint(bounds,volume);AbstractSpatialPlan result=new AbstractSpatialPlan(blueprint.getId()+":spatial",blueprint.getId(),nodes,connectors,anchors,footprint,new SiteRequirements(requirements),budget,attempts,0);List<String>errors=SpatialPlanValidator.validate(result);if(!errors.isEmpty()){events.addAll(errors);return new SpatialPlanningResult(SpatialPlanningStatus.UNPLACEABLE,result,new SpatialPlanningTrace(requestId,blueprint.getId(),seed,attempts,nodes.size(),events));}events.add("validated:local_only");return new SpatialPlanningResult(SpatialPlanningStatus.SUCCESS,result,new SpatialPlanningTrace(requestId,blueprint.getId(),seed,attempts,nodes.size(),events));}
 private static int[]size(StructureNodeType t){switch(t){case ARENA:return new int[]{16,8,16};case CORRIDOR:return new int[]{6,5,12};case ENTRANCE:return new int[]{10,6,10};case EXIT:return new int[]{8,6,8};case TRANSITION:return new int[]{6,12,6};default:return new int[]{10,6,10};}}
 private static LocalAabb connector(LocalAabb a,LocalAabb b){int minX=Math.min(a.getMin().getX(),b.getMin().getX()),minY=Math.min(a.getMin().getY(),b.getMin().getY()),minZ=Math.min(a.getMin().getZ(),b.getMin().getZ());int maxX=Math.max(a.getMax().getX(),b.getMax().getX()),maxY=Math.max(a.getMax().getY(),b.getMax().getY()),maxZ=Math.max(a.getMax().getZ(),b.getMax().getZ());return new LocalAabb(new LocalVec3i(minX+2,minY+2,minZ+2),new LocalVec3i(Math.max(minX+4,maxX-2),Math.max(minY+4,maxY-2),Math.max(minZ+4,maxZ-2)));}
 private static LocalAnchor anchor(String id,SpatialNodePlacement p){return new LocalAnchor(id,p.getSourceNodeId(),p.getPlacementId(),new LocalVec3i(p.getVolume().getMin().getX()+1,p.getVolume().getMin().getY()+1,p.getVolume().getMin().getZ()+1));}
}
