package com.sobrenaturaldirector.derivation;
import java.util.*; import com.sobrenaturaldirector.capability.CapabilityVocabulary; import com.sobrenaturaldirector.decision.model.*; import com.sobrenaturaldirector.environment.model.EnvironmentSignal; import com.sobrenaturaldirector.model.history.HistorySummary; import com.sobrenaturaldirector.model.history.HistorySummaryBuilder; import com.sobrenaturaldirector.model.player.PlayerModel; import com.sobrenaturaldirector.model.world.WorldModel; import com.sobrenaturaldirector.provider.DirectorContentProvider; import com.sobrenaturaldirector.provider.DirectorProviderRegistry;
/** Pure mapper only. It never invokes DecisionEngine. */
public final class DecisionContextAssembler {
 private final DecisionContextMetrics metrics=new DecisionContextMetrics();
 public DecisionContext assemble(PlayerModel p,WorldModel w,HistorySummary h){return assemble(p,w,h,null);}
 public DecisionContext assemble(PlayerModel p,WorldModel w,HistorySummary h,DecisionContextLiveSources sources){
  if(h==null)h=new HistorySummaryBuilder().empty(); Map<String,Long> cooldowns=new TreeMap<String,Long>(h.getCooldowns());Map<String,Double> budgets=new TreeMap<String,Double>();budgets.put("threat",10.0);
  com.sobrenaturaldirector.narrative.PacingAssessment pacing=sources==null?null:sources.getPacing();
  double pressure=pacing==null?0:clamp(1.0-pacing.getEscalationAllowance()); double tension=pressure; double recovery=pacing==null?0:pacing.getRecoveryNeed();
  if(pacing==null){metrics.tensionFallback();metrics.pressureFallback();metrics.recoveryFallback();}
  Map<String,ProviderStatus> providers=providerStatuses(sources==null?null:sources.getProviders()); if(providers.isEmpty())metrics.providerFallback();
  Set<String> content=contentTags(sources); if(content.isEmpty())metrics.contentFallback();
  Set<String> location=locationTags(sources); if(location.isEmpty())metrics.locationFallback();
  Map<String,String> provenance=new LinkedHashMap<String,String>();provenance.put("tension",pacing==null?"UNAVAILABLE":"adaptive_pacing.escalation_allowance");provenance.put("pressure",pacing==null?"UNAVAILABLE":"adaptive_pacing.escalation_allowance");provenance.put("recoveryNeed",pacing==null?"UNAVAILABLE":"adaptive_pacing.recoveryNeed");provenance.put("eventConcurrency",sources==null?"UNAVAILABLE":"director_world_lifecycle");provenance.put("providers",sources==null||sources.getProviders()==null?"UNAVAILABLE":"DirectorProviderRegistry");provenance.put("contentTags",sources==null||sources.getContentTags().isEmpty()?"UNAVAILABLE":"runtime_semantic_sources");provenance.put("locationTags",sources==null||location.isEmpty()?"UNAVAILABLE":"EnvironmentProfile");
  int events=sources==null?0:sources.getEventConcurrency(); return new DecisionContext(w==null?0:w.getWorldAgeTicks(),w==null?0:w.getWorldAgeTicks(),tension,pressure,0,recovery,value(p==null?null:p.getHealthRatio(),0),value(p==null?null:p.getCombatReadiness(),0),0,p!=null&&p.isUnderground(),false,false,events,budgets,providers,content,location,h.getClaims(),cooldowns,sources==null?null:sources.getRegion(),provenance);
 }
 public DecisionContextMetrics getMetrics(){return metrics;}
 private Map<String,ProviderStatus> providerStatuses(DirectorProviderRegistry registry){Map<String,ProviderStatus> result=new TreeMap<String,ProviderStatus>();if(registry==null)return result;boolean threat=false;ProviderStatus threatStatus=ProviderStatus.UNKNOWN;for(DirectorContentProvider p:registry.getProviders().values()){result.put(p.getProviderId().getValue(),p.getStatus());for(String capability:p.getCapabilities().keySet())if(CapabilityVocabulary.THREAT_SOURCE.getValue().equals(capability)){threat=true;threatStatus=p.getStatus();}}if(threat)result.put("HORROR",threatStatus);return result;}
 private Set<String> contentTags(DecisionContextLiveSources sources){Set<String> result=new TreeSet<String>();if(sources==null)return result;result.addAll(sources.getContentTags());DirectorProviderRegistry registry=sources.getProviders();if(registry!=null)for(DirectorContentProvider p:registry.getProviders().values())if(p.isAvailable())for(String c:p.getCapabilities().keySet()){if(CapabilityVocabulary.ACTOR_SOURCE.getValue().equals(c))result.add("ACTOR_SOURCE");if(CapabilityVocabulary.STRUCTURE_SOURCE.getValue().equals(c))result.add("STRUCTURE_SOURCE");if(CapabilityVocabulary.THREAT_SOURCE.getValue().equals(c))result.add("THREAT_SOURCE");}return result;}
 private Set<String> locationTags(DecisionContextLiveSources sources){Set<String> result=new TreeSet<String>();if(sources==null)return result;result.addAll(sources.getLocationTags());if(sources.getRegion()!=null){result.add("REGION_"+sources.getRegion().getClassification().name());for(EnvironmentSignal s:sources.getRegion().getTags())result.add(s.name());}return result;}
 private static double clamp(double x){return x<0?0:(x>1?1:x);}
 public Map<UUID,DecisionContext> assemblePerPlayer(DerivedModels models,HistorySummary h){Map<UUID,DecisionContext> r=new TreeMap<UUID,DecisionContext>();for(PlayerModel p:models.getPlayers()){WorldModel world=null;for(WorldModel x:models.getWorlds())if(x.getDimension()==p.getDimension()){world=x;break;}if(world!=null)r.put(p.getPlayerId(),assemble(p,world,h));}return Collections.unmodifiableMap(r);}
 private static double value(DerivedSignal s,double fallback){return s!=null&&s.getValue()!=null?s.getValue():fallback;}
}
