package com.sobrenaturaldirector;

import static org.junit.Assert.*;
import java.util.*;
import org.junit.Test;
import com.sobrenaturaldirector.decision.*;
import com.sobrenaturaldirector.decision.model.*;
import com.sobrenaturaldirector.derivation.*;
import com.sobrenaturaldirector.memory.*;
import com.sobrenaturaldirector.model.history.*;
import com.sobrenaturaldirector.model.player.*;
import com.sobrenaturaldirector.model.world.*;
import com.sobrenaturaldirector.observation.model.*;

public class DerivationLayerTest {
    private static final UUID ID=UUID.fromString("00000000-0000-0000-0000-000000000001");
    private static EnvironmentSnapshot env(int light,boolean sky,double y){return new EnvironmentSnapshot(1,"Plains",light,sky,y);}
    private static PlayerSnapshot player(float health,float max,int dimension,List<InventorySlotSnapshot> inventory,boolean alive){return new PlayerSnapshot(ID,"Player",dimension,10,24,20,health,max,0,0,0,false,alive,env(2,false,24),inventory);}
    private static ObservationFrame frame(PlayerSnapshot p,ObservationStatus status){return new ObservationFrame("f",10,1,Collections.singletonList(new WorldSnapshot(p==null?0:p.getDimension(),24000,12000,2,false,false,p==null?0:1)),p==null?Collections.<PlayerSnapshot>emptyList():Collections.singletonList(p),new ObservationDiagnostics(status,1,status==ObservationStatus.COMPLETE?1:0,Collections.<String>emptyList()));}
    @Test public void healthyAndLowHealthDeriveBands(){PlayerModelDeriver d=new PlayerModelDeriver();assertEquals(HealthBand.HEALTHY,d.derive(player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),false).getModel().getHealthBand());assertEquals(HealthBand.CRITICAL,d.derive(player(1,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),false).getModel().getHealthBand());}
    @Test public void healthIsBoundedAndInvalidMaxIsUnknown(){PlayerModelDeriver d=new PlayerModelDeriver();assertEquals(1.0,d.derive(player(40,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),false).getModel().getHealthRatio().getValue(),0);assertNull(d.derive(player(1,0,0,Collections.<InventorySlotSnapshot>emptyList(),true),false).getModel().getHealthRatio().getValue());}
    @Test public void unknownInventoryIsNotSemanticCapability(){List<InventorySlotSnapshot> i=Collections.singletonList(new InventorySlotSnapshot(0,"mod:gun_medkit_sword",1,0,0,false,false,"MAIN"));PlayerModel m=new PlayerModelDeriver().derive(player(20,20,0,i,true),false).getModel();assertNull(m.getRangedCapability().getValue());assertNull(m.getHealingReserve().getValue());assertNull(m.getMeleeCapability().getValue());assertEquals(1,m.getOccupiedSlots());}
    @Test public void partialModelCarriesPartialConfidence(){PlayerModel m=new PlayerModelDeriver().derive(player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),true).getModel();assertEquals(Confidence.PARTIAL,m.getOverallConfidence());assertEquals(Confidence.PARTIAL,m.getHealthRatio().getConfidence());}
    @Test public void environmentNeverClaimsCave(){EnvironmentModel m=new EnvironmentModelDeriver().derive(env(2,false,24),false);assertEquals("UNDERGROUND_LIKELY",m.getUndergroundLikely().getLabel());assertEquals("DARK_LIKELY",m.getDarkLikely().getLabel());}
    @Test public void worldTimeAndWeatherAreMathematical(){WorldModel m=new WorldModelDeriver().derive(new WorldSnapshot(-1,Long.MAX_VALUE,24001,3,true,true,0),ObservationStatus.COMPLETE);assertEquals(Long.MAX_VALUE/24000,m.getApproximateDay());assertEquals(1,m.getTimeOfDay());assertEquals(WeatherBand.THUNDER,m.getWeather());}
    @Test public void zeroPlayersAndMultipleDimensionsWork(){ObservationFrame f=new ObservationFrame("empty",0,0,Arrays.asList(new WorldSnapshot(1,5,5,1,false,false,0),new WorldSnapshot(0,5,5,1,false,false,0)),Collections.<PlayerSnapshot>emptyList(),new ObservationDiagnostics(ObservationStatus.COMPLETE,2,2,Collections.<String>emptyList()));DerivedModels d=new ObservationDerivationPipeline().derive(f);assertEquals(0,d.getPlayers().size());assertEquals(2,d.getWorlds().size());}
    @Test public void deltaDetectsHealthDimensionInventoryAndDeath(){PlayerSnapshot before=player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true);PlayerSnapshot after=player(10,20,1,Collections.singletonList(new InventorySlotSnapshot(0,"x",1,0,0,false,false,"MAIN")),false);ObservationDelta d=new ObservationDeltaCalculator().calculate(frame(before,ObservationStatus.COMPLETE),frame(after,ObservationStatus.COMPLETE));PlayerDelta x=d.getPlayers().get(0);assertTrue(x.isHealthChanged());assertTrue(x.isDimensionChanged());assertTrue(x.isInventoryChanged());assertTrue(x.isDeath());}
    @Test public void memoryCandidatesCoalesceAndStayGeneric(){PlayerSnapshot a=player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),b=player(10,20,0,Collections.singletonList(new InventorySlotSnapshot(0,"gun",1,0,0,false,false,"MAIN")),true);ObservationDelta d=new ObservationDeltaCalculator().calculate(frame(a,ObservationStatus.COMPLETE),frame(b,ObservationStatus.COMPLETE));List<MemoryCandidate> c=new MemoryCandidateGenerator().generate(d,10);assertEquals(1,c.size());assertEquals("LOW_HEALTH_EXPOSURE",c.get(0).getType());assertEquals(RetentionClass.SHORT_TERM,c.get(0).getRetention());}
    @Test public void historyIsEmptyAndImmutable(){HistorySummary h=new HistorySummaryBuilder().empty();assertTrue(h.getIntents().isEmpty());try{h.getClaims().add("x");fail();}catch(UnsupportedOperationException expected){}}
    @Test public void assemblerMapsConservativelyAndDoesNotDecide(){PlayerModel p=new PlayerModelDeriver().derive(player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),false).getModel();WorldModel w=new WorldModelDeriver().derive(new WorldSnapshot(0,0,0,0,false,false,1),ObservationStatus.COMPLETE);assertEquals(1,new DecisionContextAssembler().assemblePerPlayer(new ObservationDerivationPipeline().derive(frame(player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true),ObservationStatus.COMPLETE)),new HistorySummaryBuilder().empty()).size());DecisionContext c=new DecisionContextAssembler().assemble(p,w,new HistorySummaryBuilder().empty());assertEquals(1.0,c.getHealthRatio(),0);assertEquals(0.0,c.getCombatPower(),0);}
    @Test public void offlinePipelineReachesNoAction(){PlayerSnapshot p=player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true);DerivedModels d=new ObservationDerivationPipeline().derive(frame(p,ObservationStatus.COMPLETE));DecisionContext c=new DecisionContextAssembler().assemble(d.getPlayers().get(0),d.getWorlds().get(0),new HistorySummaryBuilder().empty());assertEquals(Intent.NO_ACTION,new DecisionEngine().decide(c,88).getSelected().getIntent());}
    @Test public void derivationIsDeterministicForTenThousandInputs(){PlayerSnapshot p=player(20,20,0,Collections.<InventorySlotSnapshot>emptyList(),true);PlayerModelDeriver d=new PlayerModelDeriver();for(int i=0;i<10000;i++){PlayerModel m=d.derive(p,i%2==0).getModel();assertEquals(1.0,m.getHealthRatio().getValue(),0);assertFalse(Double.isNaN(m.getHealthRatio().getValue()));}}
}
