package com.sobrenaturaldirector;

import static org.junit.Assert.*;
import java.util.*;
import org.junit.Test;
import com.sobrenaturaldirector.capability.*;
import com.sobrenaturaldirector.content.model.*;
import com.sobrenaturaldirector.decision.model.Intent;
import com.sobrenaturaldirector.environment.EnvironmentClassifier;
import com.sobrenaturaldirector.environment.model.*;
import com.sobrenaturaldirector.narrative.*;
import com.sobrenaturaldirector.provider.DirectorProviderRegistry;
import com.sobrenaturaldirector.situation.SituationContext;
import com.sobrenaturaldirector.situation.SituationGoal;
import com.sobrenaturaldirector.situation.SituationMemory;
import com.sobrenaturaldirector.situation.SituationMemoryEntry;

public class IntentToPlanSynthesisTest {
    private static final SituationContext CONTEXT=new SituationContext(0,100,1,1,7L,false,true,true,true,Collections.singleton("clear"));
    private static NarrativePlanSynthesisRequest request(Intent intent,DirectorProviderRegistry registry){return new NarrativePlanSynthesisRequest(intent,CONTEXT,null,registry,null,false,null,null,"stable-key",null,8,3,8);}
    @Test public void noActionProducesNoPlan(){NarrativePlanSynthesisResult r=new NarrativePlanSynthesizer().synthesize(request(Intent.NO_ACTION,new DirectorProviderRegistry()));assertEquals(NarrativePlanSynthesisResult.Status.NO_PLAN_REQUIRED,r.getStatus());assertNull(r.getCandidatePlan());}
    @Test public void investigationUsesExistingSemanticBlueprint(){DirectorProviderRegistry r=registry(true,true,false);NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(request(Intent.MYSTERY_SETUP,r));assertTrue(result.isSynthesized());assertEquals("investigation:poi-witness",result.getBlueprint().getId());assertEquals(Arrays.asList("POINT_OF_INTEREST","WITNESS","CLUE_SOURCE"),names(result.getRequiredRoles()));assertTrue(result.getCandidatePlan().isComplete());}
    @Test public void discoveryOmitsOptionalRolesAndRemainsMinimal(){NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(request(Intent.LOOT_DISCOVERY,registry(true,false,false)));assertTrue(result.isSynthesized());assertEquals("discovery:landmark",result.getBlueprint().getId());assertFalse(result.getOptionalRoles().isEmpty());assertEquals(1,result.getCandidatePlan().getSelections().size());}
    @Test public void missingActorUsesSameIntentFallback(){NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(request(Intent.MYSTERY_SETUP,registry(true,false,false)));assertTrue(result.isSynthesized());assertEquals("investigation:poi-clue",result.getBlueprint().getId());assertEquals(2,result.getFallbackCount());assertEquals("MYSTERY_SETUP",result.getCandidatePlan().getIntent().getId());}
    @Test public void noCompatibleIntentIsExplicit(){NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(request(Intent.ARC_TRANSITION,new DirectorProviderRegistry()));assertEquals(NarrativePlanSynthesisResult.Status.NO_COMPATIBLE_BLUEPRINT,result.getStatus());}
    @Test public void missingRequiredCapabilityIsExplicit(){NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(request(Intent.MYSTERY_SETUP,new DirectorProviderRegistry()));assertEquals(NarrativePlanSynthesisResult.Status.MISSING_CAPABILITY,result.getStatus());assertNull(result.getCandidatePlan());}
    @Test public void establishedBaseRejectsThreatInside(){SituationContext base=new SituationContext(0,100,1,1,7L,false,true,true,true,Collections.<String>emptySet(),baseProfile());NarrativePlanSynthesisRequest q=new NarrativePlanSynthesisRequest(Intent.BOSS_ENCOUNTER,base,null,registry(true,false,true),null,false,null,"INSIDE","base-threat",null,8,3,8);NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(q);assertEquals(NarrativePlanSynthesisResult.Status.ENVIRONMENT_REJECTED,result.getStatus());}
    @Test public void perimeterThreatCanSynthesize(){SituationContext base=new SituationContext(0,100,1,1,7L,false,true,true,true,Collections.<String>emptySet(),baseProfile());NarrativePlanSynthesisRequest q=new NarrativePlanSynthesisRequest(Intent.MINOR_ENCOUNTER,base,null,registry(true,false,true),null,false,null,"PERIMETER","perimeter",null,8,3,8);NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(q);assertTrue(result.isSynthesized());assertEquals("PERIMETER",result.getRegionRelation());}
    @Test public void identicalRequestHasStableFingerprint(){DirectorProviderRegistry registry=registry(true,true,false);NarrativePlanSynthesizer s=new NarrativePlanSynthesizer();assertEquals(s.synthesize(request(Intent.MYSTERY_SETUP,registry)).getPlanFingerprint(),s.synthesize(request(Intent.MYSTERY_SETUP,registry)).getPlanFingerprint());}
    @Test public void continuationIsRecordedWithoutThreatCreation(){NarrativePlanSynthesisRequest q=new NarrativePlanSynthesisRequest(Intent.MINOR_ENCOUNTER,CONTEXT,null,registry(true,false,true),null,true,"threat-1","PERIMETER","continuation",null,8,3,8);NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(q);assertTrue(result.isSynthesized());assertTrue(result.getReasons().contains("CONTINUATION"));}
    @Test public void recentBlueprintPenaltyLetsSameIntentAlternativeWin(){SituationMemory memory=new SituationMemory();memory.record(new SituationMemoryEntry("recent",SituationGoal.INVESTIGATION,99,1,1,"INVESTIGATION|[POINT_OF_INTEREST, WITNESS, CLUE_SOURCE]|[]|LOW",Collections.<ProviderId>emptyList(),70));NarrativePlanSynthesisRequest q=new NarrativePlanSynthesisRequest(Intent.MYSTERY_SETUP,CONTEXT,memory,registry(true,true,false),null,false,null,null,"novelty",null,8,3,8);NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(q);assertTrue(result.isSynthesized());assertEquals("investigation:poi-clue",result.getBlueprint().getId());assertEquals("MYSTERY_SETUP",result.getCandidatePlan().getIntent().getId());}
    @Test public void continuityCanOverrideRecentBlueprintPenalty(){SituationMemory memory=new SituationMemory();memory.record(new SituationMemoryEntry("recent",SituationGoal.INVESTIGATION,99,1,1,"INVESTIGATION|[POINT_OF_INTEREST, WITNESS, CLUE_SOURCE]|[]|LOW",Collections.<ProviderId>emptyList(),70));NarrativePlanSynthesisRequest q=new NarrativePlanSynthesisRequest(Intent.MYSTERY_SETUP,CONTEXT,memory,registry(true,true,false),null,true,"T1",null,"continuity-novelty",Collections.singleton("continuation:investigation:poi-witness"),8,3,8);NarrativePlanSynthesisResult result=new NarrativePlanSynthesizer().synthesize(q);assertEquals("investigation:poi-witness",result.getBlueprint().getId());assertTrue(result.getReasons().contains("CONTINUITY_OVERRIDES_NOVELTY"));}
    @Test public void blueprintHistoryIsBoundedByExistingMemory(){SituationMemory memory=new SituationMemory();for(int i=0;i<40;i++)memory.record(new SituationMemoryEntry("entry"+i,SituationGoal.INVESTIGATION,i,0,0,"history"+i,Collections.<ProviderId>emptyList(),i));assertEquals(SituationMemory.MAX_ENTRIES,memory.snapshot().size());assertEquals("entry8",memory.snapshot().get(0).getId());}
    @Test public void arbitrationNoEligibleDoesNotFabricate(){NarrativeIntentDecision d=new NarrativeIntentDecision(NarrativeIntentDecision.Status.NO_ELIGIBLE_OPPORTUNITY,Intent.NO_ACTION,null,0,0,.35,Collections.<NarrativeOpportunityEvaluation>emptyList(),Collections.singletonList("NO_ELIGIBLE_OPPORTUNITY"),"x");NarrativePlanSynthesisRequest q=new NarrativePlanSynthesisRequest(Intent.NO_ACTION,CONTEXT,null,registry(true,true,true),d,false,null,null,"no-op",null,8,3,8);assertEquals(NarrativePlanSynthesisResult.Status.NO_PLAN_REQUIRED,new NarrativePlanSynthesizer().synthesize(q).getStatus());}
    private static DirectorProviderRegistry registry(boolean structure,boolean actor,boolean threat){DirectorProviderRegistry r=new DirectorProviderRegistry();if(structure)r.registerDescriptor(descriptor("structure",CapabilityVocabulary.STRUCTURE_SOURCE,80));if(actor)r.registerDescriptor(descriptor("actor",CapabilityVocabulary.ACTOR_SOURCE,70));if(threat)r.registerDescriptor(descriptor("threat",CapabilityVocabulary.THREAT_SOURCE,60));return r;}
    private static ProviderDescriptor descriptor(String id,SemanticCapability capability,int priority){ProviderId p=new ProviderId(id);return new ProviderDescriptor(p,id,EvidenceStatus.CONFIRMED,true,com.sobrenaturaldirector.decision.model.ProviderStatus.AVAILABLE,false,Collections.<String>emptySet(),"1",Collections.singleton(new CapabilityDescriptor(capability,p,ProviderAvailability.RUNTIME_CONTROL,priority,0)),Collections.<CapabilityPolicyBinding>emptySet(),ProviderAvailability.RUNTIME_CONTROL);}
    private static SemanticRegionProfile baseProfile(){Map<EnvironmentSignal,Integer> c=new EnumMap<EnvironmentSignal,Integer>(EnvironmentSignal.class);c.put(EnvironmentSignal.STORAGE,3);c.put(EnvironmentSignal.CRAFTING,3);c.put(EnvironmentSignal.SMELTING,3);c.put(EnvironmentSignal.FORTIFICATION,8);c.put(EnvironmentSignal.SLEEPING,3);c.put(EnvironmentSignal.PLAYER_MODIFICATION,35);return new EnvironmentClassifier().classify(new EnvironmentEvidence(new RegionKey(0,1,1),100,c,512,16,1,100,false,false));}
    private static List<String> names(List<com.sobrenaturaldirector.situation.SemanticRole> roles){List<String> result=new ArrayList<String>();for(Object role:roles)result.add(role.toString());return result;}
}
