package com.sobrenaturaldirector;

import static org.junit.Assert.*;
import java.util.*;
import com.sobrenaturaldirector.decision.model.*;
import com.sobrenaturaldirector.environment.EnvironmentClassifier;
import com.sobrenaturaldirector.environment.model.*;
import com.sobrenaturaldirector.narrative.*;
import com.sobrenaturaldirector.situation.*;
import org.junit.Test;

public class NarrativeIntentArbitrationTest {
    private static CandidateAction action(String id,ActionSafety safety){return new CandidateAction(id,Intent.AMBIENT_HINT,"TEST",.5,null,null,null,safety);}
    private static NarrativeOpportunity opportunity(String id,Intent intent,double utility,double confidence,ActionSafety safety){return new NarrativeOpportunity(id,intent,utility,confidence,Collections.<String>emptySet(),Collections.singletonList("TEST_INPUT"),false,new CandidateAction(id,intent,"TEST",utility,null,null,null,safety));}
    private static NarrativeArbitrationContext context(){return new NarrativeArbitrationContext(DecisionContext.calm(100),new SituationMemory(),Collections.<String>emptySet(),null,false,null,7);}
    private static SemanticRegionProfile base(){Map<EnvironmentSignal,Integer> c=new EnumMap<EnvironmentSignal,Integer>(EnvironmentSignal.class);c.put(EnvironmentSignal.STORAGE,3);c.put(EnvironmentSignal.CRAFTING,3);c.put(EnvironmentSignal.SMELTING,3);c.put(EnvironmentSignal.FORTIFICATION,8);c.put(EnvironmentSignal.SLEEPING,3);c.put(EnvironmentSignal.PLAYER_MODIFICATION,35);return new EnvironmentClassifier().classify(new EnvironmentEvidence(new RegionKey(0,1,1),100,c,512,16,1,100,false,false));}
    @Test public void neutralContextReturnsExplicitNoAction(){NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(context(),Collections.<NarrativeOpportunity>emptyList());assertTrue(d.isNoAction());assertEquals(NarrativeIntentDecision.Status.NO_ACTION,d.getStatus());}
    @Test public void weakOpportunityLosesToNoAction(){NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(context(),Collections.singletonList(opportunity("weak",Intent.AMBIENT_HINT,.1,.2,ActionSafety.NON_DESTRUCTIVE)));assertTrue(d.isNoAction());assertTrue(d.getReasons().contains("NO_ACTION_THRESHOLD"));}
    @Test public void strongInvestigationWins(){NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(context(),Collections.singletonList(opportunity("investigation",Intent.MYSTERY_SETUP,.9,.9,ActionSafety.NON_DESTRUCTIVE)));assertEquals(Intent.MYSTERY_SETUP,d.getIntent());}
    @Test public void strongDiscoveryWinsOverWeakAmbient(){NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(context(),Arrays.asList(opportunity("ambient",Intent.AMBIENT_HINT,.4,.5,ActionSafety.NON_DESTRUCTIVE),opportunity("discovery",Intent.LOOT_DISCOVERY,.9,.9,ActionSafety.NON_DESTRUCTIVE)));assertEquals(Intent.LOOT_DISCOVERY,d.getIntent());}
    @Test public void capabilityMissingRejectsWithoutCrash(){NarrativeOpportunity o=new NarrativeOpportunity("actor",Intent.MINOR_ENCOUNTER,.9,.9,Collections.singleton("ACTOR_SOURCE"),null,false,action("actor",ActionSafety.SPAWN));NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(context(),Collections.singletonList(o));assertTrue(d.isNoAction());assertFalse(d.getEvaluations().get(0).isEligible());}
    @Test public void hardCooldownRejectsThreatAndInvestigationCanWin(){ThreatNarrativeAssessment pacing=new ThreatNarrativeAssessment(false,false,true,false,0,1,0,Collections.singletonList("THREAT_HARD_COOLDOWN"));NarrativeArbitrationContext c=new NarrativeArbitrationContext(DecisionContext.calm(100),new SituationMemory(),Collections.<String>emptySet(),pacing,false,null,7);NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(c,Arrays.asList(opportunity("threat",Intent.BOSS_ENCOUNTER,.99,.99,ActionSafety.MAJOR),opportunity("investigation",Intent.MYSTERY_SETUP,.9,.9,ActionSafety.NON_DESTRUCTIVE)));assertEquals(Intent.MYSTERY_SETUP,d.getIntent());}
    @Test public void activeNarrativePreventsDuplicateThreat(){NarrativeArbitrationContext c=new NarrativeArbitrationContext(context().getDecision(),new SituationMemory(),Collections.<String>emptySet(),null,true,"THREAT",7);NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(c,Collections.singletonList(opportunity("threat",Intent.MINOR_ENCOUNTER,.99,.99,ActionSafety.SPAWN)));assertTrue(d.isNoAction());}
    @Test public void continuationCanRemainEligible(){NarrativeOpportunity o=new NarrativeOpportunity("continue",Intent.STALKING_PRESSURE,.8,.8,Collections.<String>emptySet(),null,true,action("continue",ActionSafety.SPAWN));NarrativeArbitrationContext c=new NarrativeArbitrationContext(context().getDecision(),new SituationMemory(),Collections.<String>emptySet(),null,true,"THREAT",7);assertEquals(Intent.STALKING_PRESSURE,new NarrativeIntentArbiter().arbitrate(c,Collections.singletonList(o)).getIntent());}
    @Test public void establishedBaseHardSafetyWins(){NarrativeArbitrationContext c=new NarrativeArbitrationContext(DecisionContext.calm(100).withEnvironmentProfile(base()),new SituationMemory(),Collections.<String>emptySet(),null,false,null,7);NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(c,Collections.singletonList(opportunity("ruin",Intent.STRUCTURE_SEED,.99,.99,ActionSafety.MUTATION)));assertTrue(d.isNoAction());assertFalse(d.getEvaluations().get(0).isEligible());}
    @Test public void establishedBaseAllowsLowImpact(){NarrativeArbitrationContext c=new NarrativeArbitrationContext(DecisionContext.calm(100).withEnvironmentProfile(base()),new SituationMemory(),Collections.<String>emptySet(),null,false,null,7);assertEquals(Intent.MYSTERY_SETUP,new NarrativeIntentArbiter().arbitrate(c,Collections.singletonList(opportunity("clue",Intent.MYSTERY_SETUP,.9,.9,ActionSafety.NON_DESTRUCTIVE))).getIntent());}
    @Test public void wildernessDoesNotRejectDiscovery(){DecisionContext d=DecisionContext.calm(100).withEnvironmentProfile(new EnvironmentClassifier().classify(new EnvironmentEvidence(new RegionKey(0,0,0),100,Collections.<EnvironmentSignal,Integer>emptyMap(),512,16,0,0,false,false)));assertEquals(Intent.LOOT_DISCOVERY,new NarrativeIntentArbiter().arbitrate(new NarrativeArbitrationContext(d,new SituationMemory(),Collections.<String>emptySet(),null,false,null,7),Collections.singletonList(opportunity("find",Intent.LOOT_DISCOVERY,.8,.8,ActionSafety.MUTATION))).getIntent());}
    @Test public void repeatedIntentGetsPenalty(){SituationMemory m=new SituationMemory();m.record(new SituationMemoryEntry("r",SituationGoal.INVESTIGATION,99,0,0,"x",null,1));NarrativeArbitrationContext c=new NarrativeArbitrationContext(DecisionContext.calm(100),m,Collections.<String>emptySet(),null,false,null,7);NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(c,Collections.singletonList(opportunity("i",Intent.MYSTERY_SETUP,.7,.8,ActionSafety.NON_DESTRUCTIVE)));assertTrue(d.getEvaluations().get(0).getReasons().contains("REPETITION_PENALTY"));}
    @Test public void deterministicTieAndInputOrder(){NarrativeOpportunity a=opportunity("a",Intent.MYSTERY_SETUP,.7,.8,ActionSafety.NON_DESTRUCTIVE),b=opportunity("b",Intent.LOOT_DISCOVERY,.7,.8,ActionSafety.NON_DESTRUCTIVE);NarrativeIntentArbiter x=new NarrativeIntentArbiter();assertEquals(x.arbitrate(context(),Arrays.asList(a,b)).getIntent(),x.arbitrate(context(),Arrays.asList(b,a)).getIntent());}
    @Test public void allCandidatesCanLoseToNoActionDuringRecovery(){ThreatNarrativeAssessment p=new ThreatNarrativeAssessment(true,false,false,true,-20,1,0,Collections.singletonList("RECOVERY"));NarrativeArbitrationContext c=new NarrativeArbitrationContext(DecisionContext.calm(100),new SituationMemory(),Collections.<String>emptySet(),p,false,null,7);assertTrue(new NarrativeIntentArbiter().arbitrate(c,Collections.singletonList(opportunity("threat",Intent.MINOR_ENCOUNTER,.2,.2,ActionSafety.SPAWN))).isNoAction());}
    @Test public void boundedOpportunityCountAndNoMutation(){List<NarrativeOpportunity> list=new ArrayList<NarrativeOpportunity>();for(int i=0;i<16;i++)list.add(opportunity("o"+i,Intent.AMBIENT_HINT,.4,.4,ActionSafety.NON_DESTRUCTIVE));assertNotNull(new NarrativeIntentArbiter().arbitrate(context(),list));try{list.add(opportunity("overflow",Intent.AMBIENT_HINT,.4,.4,ActionSafety.NON_DESTRUCTIVE));new NarrativeIntentArbiter().arbitrate(context(),list);fail();}catch(IllegalArgumentException expected){}}
    @Test public void missingEnvironmentIsConservativeForHighImpact(){NarrativeOpportunity o=opportunity("boss",Intent.BOSS_ENCOUNTER,.99,.99,ActionSafety.MAJOR);NarrativeIntentDecision d=new NarrativeIntentArbiter().arbitrate(context(),Collections.singletonList(o));assertTrue(d.isNoAction());assertTrue(d.getEvaluations().get(0).getReasons().contains("ENVIRONMENT_UNKNOWN_HIGH_IMPACT"));}
}
