package com.sobrenaturaldirector;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sobrenaturaldirector.naturalpressure.*;

public final class NaturalThreatPressureTest {
    private static NaturalThreatPressureDirective d(String id, String provider, String category, NaturalThreatPressureScope scope, NaturalThreatPressureLevel level, int priority, long created, long expires) { return new NaturalThreatPressureDirective(id, provider, category, scope, level, priority, created, expires, "test"); }
    @Test public void noDirectiveIsNormal() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); assertEquals(NaturalThreatPressureLevel.NORMAL,c.resolve("fnaf","COMMON",0,1,1,10,true).getLevel()); }
    @Test public void providerWideDirectiveResolves() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("wide","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.REDUCED,1,1,100)); assertEquals(NaturalThreatPressureLevel.REDUCED,c.resolve("fnaf","COMMON",0,99,99,10,true).getLevel()); }
    @Test public void categoryDirectiveResolves() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("rare","fnaf","RARE",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.ELEVATED,1,1,100)); assertEquals(NaturalThreatPressureLevel.ELEVATED,c.resolve("fnaf","RARE",0,0,0,10,true).getLevel()); assertEquals(NaturalThreatPressureLevel.NORMAL,c.resolve("fnaf","COMMON",0,0,0,10,true).getLevel()); }
    @Test public void regionalInsideMatchesOutsideDoesNot() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("region","fnaf","",NaturalThreatPressureScope.region(0,2,4,3,5),NaturalThreatPressureLevel.SUPPRESSED,1,1,100)); assertEquals(NaturalThreatPressureLevel.SUPPRESSED,c.resolve("fnaf","COMMON",0,3,4,10,true).getLevel()); assertEquals(NaturalThreatPressureLevel.NORMAL,c.resolve("fnaf","COMMON",0,5,4,10,true).getLevel()); }
    @Test public void dimensionMismatchDoesNotMatch() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("nether","fnaf","",NaturalThreatPressureScope.world(-1),NaturalThreatPressureLevel.SUPPRESSED,1,1,100)); assertEquals(NaturalThreatPressureLevel.NORMAL,c.resolve("fnaf","COMMON",0,0,0,10,true).getLevel()); }
    @Test public void expiryRestoresNormal() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("short","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.ELEVATED,1,1,10)); assertEquals(NaturalThreatPressureLevel.NORMAL,c.resolve("fnaf","COMMON",0,0,0,10,true).getLevel()); assertTrue(c.getDirectives().isEmpty()); }
    @Test public void explicitRemovalRestoresNormal() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("remove","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.SUPPRESSED,1,1,100)); assertTrue(c.remove("remove")); assertEquals(NaturalThreatPressureLevel.NORMAL,c.resolve("fnaf","COMMON",0,0,0,10,true).getLevel()); }
    @Test public void sameIdUpdateIsIdempotent() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("same","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.REDUCED,1,1,100)); c.put(d("same","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.ELEVATED,1,2,100)); assertEquals(1,c.getDirectives().size()); assertEquals(NaturalThreatPressureLevel.ELEVATED,c.resolve("fnaf","COMMON",0,0,0,10,true).getLevel()); }
    @Test public void priorityWinsDeterministically() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("low","fnaf","",NaturalThreatPressureScope.region(0,0,10,0,10),NaturalThreatPressureLevel.SUPPRESSED,1,1,100)); c.put(d("high","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.ELEVATED,2,1,100)); assertEquals(NaturalThreatPressureLevel.ELEVATED,c.resolve("fnaf","COMMON",0,1,1,10,true).getLevel()); }
    @Test public void regionSpecificityWinsPriorityTie() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("wide","fnaf","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.REDUCED,2,1,100)); c.put(d("local","fnaf","",NaturalThreatPressureScope.region(0,0,10,0,10),NaturalThreatPressureLevel.SUPPRESSED,2,1,100)); assertEquals(NaturalThreatPressureLevel.SUPPRESSED,c.resolve("fnaf","COMMON",0,1,1,10,true).getLevel()); }
    @Test public void absentProviderIsNormalAndNonCrashing() { NaturalThreatPressureCoordinator c=new NaturalThreatPressureCoordinator(); c.put(d("absent","missing","",NaturalThreatPressureScope.world(0),NaturalThreatPressureLevel.SUPPRESSED,1,1,100)); NaturalThreatPressureResolution r=c.resolve("missing","COMMON",0,0,0,10,false); assertEquals(NaturalThreatPressureLevel.NORMAL,r.getLevel()); assertFalse(r.isProviderAvailable()); }
    @Test public void nbtRoundTripPreservesDirective() { NaturalThreatPressureDirective original=d("nbt","fnaf","COMMON",NaturalThreatPressureScope.region(0,1,2,3,4),NaturalThreatPressureLevel.STRONGLY_REDUCED,4,5,100); NaturalThreatPressureDirective copy=NaturalThreatPressureDirective.fromNbt(original.toNbt()); assertEquals(original.getDirectiveId(),copy.getDirectiveId()); assertEquals(original.getProvider(),copy.getProvider()); assertEquals(original.getCategory(),copy.getCategory()); assertEquals(original.getLevel(),copy.getLevel()); assertEquals(original.getScope().getMaxChunkZ(),copy.getScope().getMaxChunkZ()); }
    @Test public void allLevelsAreSemanticAndBounded() { assertEquals(5,NaturalThreatPressureLevel.values().length); assertFalse(java.util.Arrays.asList(NaturalThreatPressureLevel.values()).toString().contains("MAXIMUM")); }
    @Test public void autonomousPressureIsDisabled() { assertFalse(NaturalThreatPressureRuntime.isAutonomousPressureEnabled()); }
}
