package com.sobrenaturaldirector;

import static org.junit.Assert.*;
import java.util.*;
import org.junit.Test;
import com.sobrenaturaldirector.content.catalog.*;
import com.sobrenaturaldirector.content.model.*;
import com.sobrenaturaldirector.content.query.*;
import com.sobrenaturaldirector.content.resolver.*;
import com.sobrenaturaldirector.planner.requirement.PlanRequirement;
import com.sobrenaturaldirector.planner.model.RequirementStatus;
import com.sobrenaturaldirector.decision.model.ProviderStatus;

public class SemanticContentResolverTest {
    private static final ProviderId VANILLA=new ProviderId("minecraft");
    private static final SemanticCapability HOSTILE=new SemanticCapability("content:common_hostile");
    private static final SemanticCapability UNDEAD=new SemanticCapability("theme:undead");
    private static ProviderDescriptor provider(ProviderId id){return new ProviderDescriptor(id,id.getValue(),EvidenceStatus.CONFIRMED,true,ProviderStatus.UNKNOWN,false,Collections.singleton("PHASE_0D2"));}
    private static SemanticContentEntry entity(String key,ProviderId p,SemanticCapability... caps){return new SemanticContentEntry(new ContentKey(key),p,ContentKind.ENTITY,Arrays.asList(caps),EvidenceStatus.CONFIRMED,Provenance.VANILLA_BUILTIN,true,false,ExecutionStatus.NOT_EVALUATED,Collections.singleton("FOUNDATION_BUILTIN_MAPPING"));}
    private static SemanticCatalog catalog(SemanticContentEntry... entries){Set<ProviderId>ids=new HashSet<ProviderId>();List<ProviderDescriptor>ps=new ArrayList<ProviderDescriptor>();for(SemanticContentEntry e:entries)if(ids.add(e.getProvider()))ps.add(provider(e.getProvider()));return new SemanticCatalog(ps,Arrays.asList(entries));}
    private static ResolutionRequest request(SemanticCapability... caps){return new ResolutionRequest(Arrays.asList(caps),Collections.<SemanticCapability>emptyList(),Collections.singleton(ContentKind.ENTITY),Collections.<ProviderId>emptyList(),Collections.<ProviderId>emptySet(),EvidenceStatus.STATIC_CANDIDATE,ResolutionRequest.AdapterPolicy.REJECT,ResolutionRequest.FallbackPolicy.NONE);}
    private static RuntimeContentIndex runtime(ProviderId p,ContentKey... keys){Map<ProviderId,ProviderStatus>m=new HashMap<ProviderId,ProviderStatus>();m.put(p,ProviderStatus.AVAILABLE);return new RuntimeContentIndex(m,Collections.<ContentKey>emptyList(),Collections.<ContentKey>emptyList(),Arrays.asList(keys));}

    @Test public void exactAndAllOfResolution(){SemanticContentEntry z=entity("minecraft:zombie",VANILLA,HOSTILE,UNDEAD);ResolutionResult r=new SemanticContentResolver().resolve(request(HOSTILE,UNDEAD),catalog(z),runtime(VANILLA,z.getKey()));assertEquals(ResolutionResult.Status.RESOLVED,r.getStatus());}
    @Test public void multipleCandidatesAreReturned(){SemanticContentEntry z=entity("minecraft:zombie",VANILLA,HOSTILE),s=entity("minecraft:skeleton",VANILLA,HOSTILE);ResolutionResult r=new SemanticContentResolver().resolve(request(HOSTILE),catalog(z,s),runtime(VANILLA,z.getKey(),s.getKey()));assertEquals(ResolutionResult.Status.MULTIPLE_CANDIDATES,r.getStatus());assertEquals(2,r.getCandidates().size());}
    @Test public void missingProviderNeverBecomesAvailable(){SemanticContentEntry z=entity("minecraft:zombie",VANILLA,HOSTILE);Map<ProviderId,ProviderStatus>m=new HashMap<ProviderId,ProviderStatus>();m.put(VANILLA,ProviderStatus.MISSING);ResolutionResult r=new SemanticContentResolver().resolve(request(HOSTILE),catalog(z),new RuntimeContentIndex(m,null,null,null));assertEquals(ResolutionResult.Status.PROVIDER_MISSING,r.getStatus());}
    @Test public void missingEntryIsDistinct(){SemanticContentEntry z=entity("minecraft:zombie",VANILLA,HOSTILE);ResolutionResult r=new SemanticContentResolver().resolve(request(HOSTILE),catalog(z),runtime(VANILLA));assertEquals(ResolutionResult.Status.CONTENT_MISSING,r.getStatus());}
    @Test public void unknownRuntimeDoesNotPromoteStatic(){SemanticContentEntry z=entity("minecraft:zombie",VANILLA,HOSTILE);ResolutionResult r=new SemanticContentResolver().resolve(request(HOSTILE),catalog(z),null);assertEquals(ResolutionResult.Status.UNKNOWN,r.getStatus());assertEquals(AvailabilityStatus.UNKNOWN,r.getCandidates().get(0).getAvailability());}
    @Test public void adapterRequiredIsNotDirectAvailability(){ProviderId g=new ProviderId("gravestone");SemanticContentEntry c=new SemanticContentEntry(new ContentKey("gravestone:catacomb"),g,ContentKind.STRUCTURE_CAPABILITY,Collections.singleton(new SemanticCapability("structure:catacomb")),EvidenceStatus.CONFIRMED,Provenance.ORIGINAL_MOD_AUDIT,false,true,ExecutionStatus.ADAPTER_REQUIRED,Collections.singleton("PHASE_0B_CAPABILITIES"));ResolutionResult r=new SemanticContentResolver().resolve(new ResolutionRequest(Collections.singleton(new SemanticCapability("structure:catacomb")),null,Collections.singleton(ContentKind.STRUCTURE_CAPABILITY),null,null,EvidenceStatus.STATIC_CANDIDATE,ResolutionRequest.AdapterPolicy.ALLOW,ResolutionRequest.FallbackPolicy.NONE),catalog(c),runtime(g));assertEquals(ResolutionResult.Status.ADAPTER_REQUIRED,r.getStatus());}
    @Test public void arbitraryNameDoesNotInferWeapon(){SemanticContentEntry e=entity("test:super_gun",VANILLA);ResolutionResult r=new SemanticContentResolver().resolve(request(new SemanticCapability("content:weapon")),catalog(e),runtime(VANILLA,e.getKey()));assertEquals(ResolutionResult.Status.UNRESOLVED,r.getStatus());}
    @Test public void duplicateContentRejected(){SemanticContentEntry a=entity("minecraft:zombie",VANILLA,HOSTILE);try{catalog(a,a);fail();}catch(IllegalArgumentException expected){}}
    @Test public void duplicateProviderRejected(){ProviderDescriptor p=provider(VANILLA);try{new SemanticCatalog(Arrays.asList(p,p),Collections.<SemanticContentEntry>emptyList());fail();}catch(IllegalArgumentException expected){}}
    @Test public void unknownProviderRejected(){try{new SemanticCatalog(Collections.singleton(provider(VANILLA)),Collections.singleton(entity("other:zombie",new ProviderId("other"),HOSTILE)));fail();}catch(IllegalArgumentException expected){}}
    @Test public void collectionsAreImmutable(){SemanticContentEntry e=entity("minecraft:zombie",VANILLA,HOSTILE);SemanticCatalog c=catalog(e);try{c.getEntries().clear();fail();}catch(UnsupportedOperationException expected){}RuntimeContentIndex i=runtime(VANILLA,e.getKey());try{i.getEntities().clear();fail();}catch(UnsupportedOperationException expected){}}
    @Test public void orderingIsStable(){SemanticContentEntry a=entity("minecraft:zombie",VANILLA,HOSTILE),b=entity("minecraft:skeleton",VANILLA,HOSTILE);ResolutionResult x=new SemanticContentResolver().resolve(request(HOSTILE),catalog(a,b),runtime(VANILLA,a.getKey(),b.getKey()));ResolutionResult y=new SemanticContentResolver().resolve(request(HOSTILE),catalog(b,a),runtime(VANILLA,b.getKey(),a.getKey()));assertEquals(x.getCandidates().get(0).getEntry().getKey(),y.getCandidates().get(0).getEntry().getKey());}
    @Test public void propertyDeterminismTenThousandCases(){SemanticContentEntry e=entity("minecraft:zombie",VANILLA,HOSTILE);SemanticCatalog c=catalog(e);RuntimeContentIndex i=runtime(VANILLA,e.getKey());for(int n=0;n<10000;n++){ResolutionResult r=new SemanticContentResolver().resolve(request(HOSTILE),c,i);assertEquals(ResolutionResult.Status.RESOLVED,r.getStatus());assertEquals("minecraft:zombie",r.getCandidates().get(0).getEntry().getKey().getValue());}}
    @Test public void curatedResourceLoadsAndValidates(){SemanticCatalog c=SemanticCatalogResource.load(getClass().getClassLoader());new SemanticCatalogValidator().validate(c);assertEquals(44,c.getEntries().size());assertTrue(c.getProviders().containsKey(new ProviderId("customnpcs")));assertTrue(c.getEntries().containsKey(new ContentKey("slenderman:threat")));assertFalse(c.getEntries().containsKey(new ContentKey("director:woodpecker")));}
    @Test public void plannerRequirementUsesCanonicalCapability(){ResolutionRequest r=PlanRequirementResolution.requestFor(new PlanRequirement("x","STRUCTURE_THEME:CEMETERY",RequirementStatus.DEFERRED,false,null));assertTrue(r.getRequired().contains(new SemanticCapability("theme:cemetery")));}
    @Test public void enrichedCatalogIsDeterministicForTenThousandResolutions(){SemanticCatalog c=SemanticCatalogResource.load(getClass().getClassLoader());RuntimeContentIndex i=runtime(new ProviderId("minecraft"),new ContentKey("minecraft:zombie"),new ContentKey("minecraft:skeleton"));ResolutionRequest q=request(HOSTILE);for(int n=0;n<10000;n++){ResolutionResult r=new SemanticContentResolver().resolve(q,c,i);assertEquals(ResolutionResult.Status.MULTIPLE_CANDIDATES,r.getStatus());assertEquals("minecraft:skeleton",r.getCandidates().get(0).getEntry().getKey().getValue());}}
}
