package com.sobrenaturaldirector;

import static org.junit.Assert.*;import java.util.*;import org.junit.Test;
import com.sobrenaturaldirector.composition.*;import com.sobrenaturaldirector.composition.model.*;import com.sobrenaturaldirector.mutation.*;import com.sobrenaturaldirector.mutation.model.*;import com.sobrenaturaldirector.mutation.safety.*;import com.sobrenaturaldirector.mutation.validation.*;import com.sobrenaturaldirector.planner.model.*;import com.sobrenaturaldirector.planner.requirement.*;import com.sobrenaturaldirector.spatial.*;import com.sobrenaturaldirector.spatial.model.*;import com.sobrenaturaldirector.spatial.validation.*;

public class SpatialMutationTest {
 private static CompositionResult composition(String theme){List<PlanRequirement>r=Arrays.asList(new PlanRequirement("location","LOCATION:UNDERGROUND",RequirementStatus.SATISFIED,false,null),new PlanRequirement("common","CONTENT_ROLE:COMMON_HOSTILE",RequirementStatus.DEFERRED,false,null),new PlanRequirement("boss","CONTENT_ROLE:BOSS",RequirementStatus.DEFERRED,false,null));DirectorPlan p=new DirectorPlan("plan:boss","decision",com.sobrenaturaldirector.decision.model.Intent.BOSS_ENCOUNTER,"goal",PlanHorizon.SHORT,PlanStatus.TENTATIVE,Collections.<PlanStep>emptyList(),r,null,"fingerprint",null,null);return new CompositionEngine().compose(new CompositionRequest(p,theme,StructureScale.MEDIUM,9,null));}
 private static CompositionResult catacomb(){return composition("catacomb");}
 @Test public void spatialPlanIsLocalAndValidated(){CompositionResult c=catacomb();SpatialPlanningResult r=new AbstractSpatialPlanner().plan("request",c.getStructure(),c.getEncounters(),c.getRewards(),SpatialBudget.TECHNICAL_COMPOSITION_DEFAULT,9,false);assertEquals(SpatialPlanningStatus.SUCCESS,r.getStatus());assertEquals(0,SpatialPlanValidator.validate(r.getPlan()).size());assertEquals(0,r.getPlan().getLocalOrigin().getX());assertTrue(r.getPlan().getFootprint().getBounds().getMin().getY()<=0);}
 @Test public void transactionIsAcyclicAndNotReadyForRuntime(){CompositionResult c=catacomb();AbstractSpatialPlan s=new AbstractSpatialPlanner().plan("request",c.getStructure(),c.getEncounters(),c.getRewards(),SpatialBudget.TECHNICAL_COMPOSITION_DEFAULT,9,false).getPlan();MutationBudget b=new MutationBudget(2000000,128,512,0,256,512,64);MutationTransactionPlan p=new MutationTransactionPlanner().plan("tx",s,b);assertTrue(MutationPlanValidator.validate(p).isEmpty());assertEquals(MutationSafetyAssessment.Status.REQUIRES_RUNTIME_VALIDATION,p.getSafety().getStatus());assertEquals(ExecutionReadiness.SITE_REQUIRED,p.getSafety().getReadiness());}
 @Test public void noStructureProducesNoMutationIntents(){MutationTransactionPlan p=new MutationTransactionPlanner().plan("empty",null,new MutationBudget(1,1,1,0,4,4,1));assertTrue(p.getIntents().isEmpty());assertTrue(MutationPlanValidator.validate(p).isEmpty());}
 @Test public void thousandSeedSweepAcrossThemes(){for(String theme:Arrays.asList("catacomb","pizzeria","lab","generic"))for(int seed=0;seed<1000;seed++){CompositionResult c=composition(theme);SpatialPlanningResult r=new AbstractSpatialPlanner().plan("sweep",c.getStructure(),c.getEncounters(),c.getRewards(),SpatialBudget.TECHNICAL_COMPOSITION_DEFAULT,seed,false);assertEquals(theme+":"+seed,SpatialPlanningStatus.SUCCESS,r.getStatus());assertTrue(SpatialPlanValidator.validate(r.getPlan()).isEmpty());MutationTransactionPlan tx=new MutationTransactionPlanner().plan("tx:"+theme+":"+seed,r.getPlan(),new MutationBudget(2000000,128,512,0,256,512,64));assertTrue(MutationPlanValidator.validate(tx).isEmpty());}}
}
