package com.sobrenaturaldirector.threat;

public enum ThreatLifecycleState {
    PLANNED, AUTHORIZED, MATERIALIZING, MATERIALIZED, TEMPORARILY_UNBOUND,
    RECONCILING, SUSPENDED, RESOLVING, PREPARED, ACTIVE, RESOLVED, STALE,
    MISSING, OWNERSHIP_MISMATCH, FAILED
}
