package com.sobrenaturaldirector.narrative;
import java.util.*;import com.sobrenaturaldirector.persistence.DirectorWorldSavedData;
/** Provider-neutral semantic thread ledger; it never executes or scans Minecraft. */
public final class NarrativeThreadManager{
 public static final int MAX_THREADS=16,MAX_PROCESSED=8;
 public PersistentNarrativeThread create(DirectorWorldSavedData data,String id,String subject,int dimension,int regionX,int regionZ,Set<String> tags,long tick,String reason){if(data==null)throw new IllegalArgumentException("data required");PersistentNarrativeThread old=data.getNarrativeThread(id);if(old!=null)return old;if(data.getNarrativeThreads().size()>=MAX_THREADS)throw new IllegalStateException("thread limit reached");PersistentNarrativeThread t=new PersistentNarrativeThread(id,subject,NarrativeThreadState.ACTIVE,tick,tick,tick,dimension,regionX,regionZ,tags,"",Collections.<NarrativeThreadPlanHistory>emptyList(),Collections.<String>emptyList(),reason==null?Collections.<String>emptyList():Collections.singletonList(reason));data.recordNarrativeThread(t);return t;}
 public NarrativeThreadAffinity affinity(PersistentNarrativeThread t,String narrativeId,String subject,Set<String> tags,int dimension,int regionX,int regionZ){if(t==null||t.isTerminal())return new NarrativeThreadAffinity("",0,false,Collections.singletonList("THREAD_NOT_ACTIVE"));int score=0;List<String> r=new ArrayList<String>();if(narrativeId!=null&&narrativeId.length()>0&&narrativeId.equals(t.getSubject())){score+=100;r.add("SHARED_UNRESOLVED_IDENTITY");}if(subject!=null&&subject.length()>0&&subject.equals(t.getSubject())){score+=60;r.add("SHARED_SUBJECT");}int shared=0;for(String tag:tags==null?Collections.<String>emptySet():tags)if(t.getTags().contains(tag))shared++;if(shared>0){score+=shared*20;r.add("SHARED_TAGS:"+shared);}if(score>0&&t.getDimension()==dimension&&t.getRegionX()==regionX&&t.getRegionZ()==regionZ){score+=10;r.add("SAME_REGION_SUPPORT");}return new NarrativeThreadAffinity(t.getId(),score,score>=60,r);}
 public PersistentNarrativeThread attach(DirectorWorldSavedData data,String threadId,PersistentNarrativePlan plan,long tick,String reason){PersistentNarrativeThread t=data.getNarrativeThread(threadId);if(t==null)throw new IllegalArgumentException("thread not found");PersistentNarrativePlan linked=plan.withThreadId(threadId);data.updateNarrativePlan(linked);data.updateNarrativeThread(t.attach(plan.getId(),plan.getIntent(),plan.getBlueprintId(),tick,reason));return data.getNarrativeThread(threadId);}
 public NarrativeThreadArbitrationContext arbitrationContext(DirectorWorldSavedData data,String threadId){PersistentNarrativeThread t=data==null?null:data.getNarrativeThread(threadId);if(t==null)throw new IllegalArgumentException("thread not found");PersistentNarrativePlan p=t.getCurrentPlanId().length()==0?null:data.getNarrativePlan(t.getCurrentPlanId());return new NarrativeThreadArbitrationContext(t,p==null?"":p.getIntent());}
 public PersistentNarrativePlan replan(DirectorWorldSavedData data,String threadId,PersistentNarrativePlan oldPlan,NarrativePlanSynthesisRequest request,NarrativePlanSynthesizer synthesizer,com.sobrenaturaldirector.provider.DirectorProviderRegistry registry,long tick,long expiryTick){if(data.getNarrativeThread(threadId)==null)throw new IllegalArgumentException("thread not found");PersistentNarrativePlan replacement=new NarrativePlanLifecycleCoordinator().replan(oldPlan,request,synthesizer,registry,data,tick,expiryTick);if(replacement!=null){PersistentNarrativeThread thread=data.getNarrativeThread(threadId);data.updateNarrativeThread(thread.attach(replacement.getId(),replacement.getIntent(),replacement.getBlueprintId(),tick,"REPLAN_REPLACEMENT"));}return replacement;}
 public PersistentNarrativeThread dormant(DirectorWorldSavedData data,String id,long tick){return transition(data,id,NarrativeThreadState.DORMANT,tick,"NO_MEANINGFUL_OPPORTUNITY");}public PersistentNarrativeThread resume(DirectorWorldSavedData data,String id,long tick,String reason){return transition(data,id,NarrativeThreadState.ACTIVE,tick,reason==null?"RELATED_EVIDENCE_RETURNED":reason);}public PersistentNarrativeThread resolve(DirectorWorldSavedData data,String id,long tick,String reason){return transition(data,id,NarrativeThreadState.RESOLVED,tick,reason==null?"EXPLICIT_SEMANTIC_RESOLUTION":reason);}
 private PersistentNarrativeThread transition(DirectorWorldSavedData d,String id,NarrativeThreadState s,long tick,String reason){PersistentNarrativeThread t=d.getNarrativeThread(id);if(t==null)throw new IllegalArgumentException("thread not found");PersistentNarrativeThread n=t.assess(s,tick,reason);if(n.getState()!=t.getState()||!n.getReasons().equals(t.getReasons()))d.updateNarrativeThread(n);return n;}
 public int evaluateBounded(DirectorWorldSavedData data,ThreadAssessment assessment,long tick){if(data==null||assessment==null)return 0;List<PersistentNarrativeThread> values=new ArrayList<PersistentNarrativeThread>(data.getNarrativeThreads());Collections.sort(values,new Comparator<PersistentNarrativeThread>(){public int compare(PersistentNarrativeThread a,PersistentNarrativeThread b){int state=Integer.compare(a.getState().isTerminal()?2:a.getState()==NarrativeThreadState.ACTIVE?0:1,b.getState().isTerminal()?2:b.getState()==NarrativeThreadState.ACTIVE?0:1);return state!=0?state:a.getId().compareTo(b.getId());}});int count=0;for(PersistentNarrativeThread t:values){if(count>=MAX_PROCESSED)break;if(!t.isTerminal()){assessment.assess(t,tick);count++;}}return count;}
 public interface ThreadAssessment{void assess(PersistentNarrativeThread thread,long tick);}
}
