package com.sobrenaturaldirector.narrative;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.sobrenaturaldirector.capability.CandidatePlan;
import com.sobrenaturaldirector.capability.CapabilityDescriptor;
import com.sobrenaturaldirector.capability.CapabilityQuery;
import com.sobrenaturaldirector.capability.CapabilityVocabulary;
import com.sobrenaturaldirector.capability.SituationIntent;
import com.sobrenaturaldirector.content.model.SemanticCapability;
import com.sobrenaturaldirector.decision.model.ActionSafety;
import com.sobrenaturaldirector.decision.model.CandidateAction;
import com.sobrenaturaldirector.planning.environment.EnvironmentActionImpact;
import com.sobrenaturaldirector.planning.environment.EnvironmentPlanningAssessment;
import com.sobrenaturaldirector.planning.environment.PlayerAreaSafetyPolicy;
import com.sobrenaturaldirector.situation.RoleCapabilityResolver;
import com.sobrenaturaldirector.situation.SemanticRole;
import com.sobrenaturaldirector.situation.SituationBlueprint;
import com.sobrenaturaldirector.situation.SituationBlueprintComposer;
import com.sobrenaturaldirector.situation.SituationGoal;

/** Bounded semantic intent-to-plan synthesis. It produces data only. */
public final class NarrativePlanSynthesizer {
    public static final int DEFAULT_MAX_BLUEPRINTS=8, DEFAULT_MAX_FALLBACKS=3, DEFAULT_MAX_PROVIDERS=8;
    private final SituationBlueprintComposer composer=new SituationBlueprintComposer(); private final RoleCapabilityResolver roles=new RoleCapabilityResolver(); private final PlayerAreaSafetyPolicy safety=new PlayerAreaSafetyPolicy();

    public NarrativePlanSynthesisResult synthesize(NarrativePlanSynthesisRequest request){
        if(request==null)return invalid();
        if(request.getArbitration()!=null&&request.getArbitration().getIntent()!=request.getIntent())return failure(request,NarrativePlanSynthesisResult.Status.INVALID_INPUT,null,"INTENT_MISMATCH",Collections.<String>emptyList(),0,null,null);
        if(request.getIntent()==com.sobrenaturaldirector.decision.model.Intent.NO_ACTION||request.getArbitration()!=null&&request.getArbitration().getStatus()!=NarrativeIntentDecision.Status.INTENT_SELECTED)return failure(request,NarrativePlanSynthesisResult.Status.NO_PLAN_REQUIRED,null,"ARBITRATION_NO_PLAN",Collections.<String>emptyList(),0,null,null);
        SituationGoal goal=goal(request.getIntent());if(goal==null)return failure(request,NarrativePlanSynthesisResult.Status.NO_COMPATIBLE_BLUEPRINT,null,"NO_INTENT_BLUEPRINT_FAMILY",Collections.<String>emptyList(),0,null,null);
        List<SituationBlueprint> blueprints=new ArrayList<SituationBlueprint>(composer.blueprintsFor(goal));if(goal==SituationGoal.INVESTIGATION)blueprints.add(new SituationBlueprint("investigation:poi-clue",goal,java.util.Arrays.asList(SemanticRole.POINT_OF_INTEREST,SemanticRole.CLUE_SOURCE),Collections.<SemanticRole>emptyList(),com.sobrenaturaldirector.situation.SituationIntensity.LOW,62,0));final NarrativePlanSynthesisRequest stableRequest=request;Collections.sort(blueprints,new java.util.Comparator<SituationBlueprint>(){public int compare(SituationBlueprint a,SituationBlueprint b){int as=a.getBaseScore()-stableRequest.getMemory().recentBlueprintCount(a.fingerprint(),stableRequest.getSituation().getTick(),24000L)*20;int bs=b.getBaseScore()-stableRequest.getMemory().recentBlueprintCount(b.fingerprint(),stableRequest.getSituation().getTick(),24000L)*20;if(stableRequest.isContinuation()&&stableRequest.getTags().contains("continuation:"+a.getId()))as+=1000;if(stableRequest.isContinuation()&&stableRequest.getTags().contains("continuation:"+b.getId()))bs+=1000;int result=Integer.compare(bs,as);return result!=0?result:a.getId().compareTo(b.getId());}});List<String> attempts=new ArrayList<String>();int considered=0,fallbacks=0;boolean sawMissing=false,sawEnvironment=false;NarrativePlanSynthesisResult.Status terminal=NarrativePlanSynthesisResult.Status.NO_VALID_COMPOSITION;
        for(SituationBlueprint blueprint:blueprints){if(considered++>=request.getMaxBlueprints())break;if(considered>1&&fallbacks>=request.getMaxFallbacks())break;List<String> reasons=new ArrayList<String>();reasons.add("INTENT_COMPATIBLE:"+goal);ActionSafety actionSafety=impactSafety(blueprint);String relation=relation(request,blueprint);EnvironmentPlanningAssessment environment=safety.assess(request.getSituation().getRegionProfile(),action(blueprint,request.getIntent(),actionSafety,relation));reasons.addAll(environment.getReasons());if(!environment.isAllowed()){attempts.add(blueprint.getId()+" REJECTED ENVIRONMENT "+environment.getReasons());terminal=environment.isHardRejected()?NarrativePlanSynthesisResult.Status.ENVIRONMENT_REJECTED:NarrativePlanSynthesisResult.Status.NO_VALID_COMPOSITION;fallbacks++;continue;}
            List<SemanticCapability> required=roles.required(blueprint.getRequiredRoles());Map<SemanticCapability,CapabilityDescriptor> selections=new LinkedHashMap<SemanticCapability,CapabilityDescriptor>();boolean missing=false;for(SemanticCapability capability:required){List<CapabilityDescriptor> found=request.getRegistry().query(new CapabilityQuery(capability));if(found.isEmpty()){missing=true;reasons.add("MISSING_REQUIRED_CAPABILITY:"+capability);break;}if(found.size()>request.getMaxProviders())found=found.subList(0,request.getMaxProviders());selections.put(capability,found.get(0));}
            if(missing){attempts.add(blueprint.getId()+" REJECTED MISSING_CAPABILITY "+reasons);terminal=NarrativePlanSynthesisResult.Status.MISSING_CAPABILITY;fallbacks++;continue;}
            reasons.add("REQUIRED_ROLES_SATISFIED");int repeatedBlueprint=request.getMemory().recentBlueprintCount(blueprint.fingerprint(),request.getSituation().getTick(),24000L);if(repeatedBlueprint>0){reasons.add("BLUEPRINT_REPETITION_PENALTY:-"+(repeatedBlueprint*20));if(request.isContinuation()&&request.getTags().contains("continuation:"+blueprint.getId()))reasons.add("CONTINUITY_OVERRIDES_NOVELTY");}reasons.add("OPTIONAL_ROLES_OMITTED_MINIMAL_PLAN:"+blueprint.getOptionalRoles());reasons.add(request.isContinuation()?"CONTINUATION":"NEW_NARRATIVE");if(environment.isPerimeterPreferred())reasons.add("REGION_RELATION_PERIMETER");
            SituationIntent planIntent=new SituationIntent(request.getIntent().name(),required);CandidatePlan plan=new CandidatePlan(planIntent,selections,Collections.unmodifiableList(reasons));String fingerprint=fingerprint(request,blueprint,relation,selections);return new NarrativePlanSynthesisResult(NarrativePlanSynthesisResult.Status.SYNTHESIZED,request,blueprint,plan,blueprint.getRequiredRoles(),blueprint.getOptionalRoles(),selections,reasons,attempts,fallbacks,relation,environment.getImpact(),fingerprint);
        }
        if(attempts.toString().contains("MISSING_CAPABILITY"))terminal=NarrativePlanSynthesisResult.Status.MISSING_CAPABILITY;else if(attempts.toString().contains("ENVIRONMENT"))terminal=NarrativePlanSynthesisResult.Status.ENVIRONMENT_REJECTED;return failure(request,terminal,null,terminal.name(),attempts,fallbacks,null,null);
    }
    private static SituationGoal goal(com.sobrenaturaldirector.decision.model.Intent intent){switch(intent){case MYSTERY_SETUP:case MYSTERY_PAYOFF:return SituationGoal.INVESTIGATION;case LOOT_DISCOVERY:case STRUCTURE_REVEAL:case STRUCTURE_SEED:return SituationGoal.DISCOVERY;case MINOR_ENCOUNTER:case AMBUSH:case BOSS_ENCOUNTER:case HORROR_REVEAL:case STALKING_PRESSURE:return SituationGoal.THREAT_EVENT;case AMBIENT_HINT:case RECOVERY:return SituationGoal.AMBIENT_EVENT;default:return null;}}
    private static ActionSafety impactSafety(SituationBlueprint blueprint){if(blueprint.getRequiredRoles().contains(SemanticRole.THREAT))return ActionSafety.SPAWN;if(blueprint.getRequiredRoles().contains(SemanticRole.RUIN))return ActionSafety.MUTATION;return ActionSafety.NON_DESTRUCTIVE;}
    private static String relation(NarrativePlanSynthesisRequest request,SituationBlueprint blueprint){if(request.getRegionRelation().length()>0)return request.getRegionRelation();return blueprint.getRequiredRoles().contains(SemanticRole.THREAT)?"PERIMETER":"INSIDE";}
    private static CandidateAction action(SituationBlueprint blueprint,com.sobrenaturaldirector.decision.model.Intent intent,ActionSafety safety,String relation){Map<String,String> metadata=new LinkedHashMap<String,String>();metadata.put("blueprintId",blueprint.getId());metadata.put("environmentRelation",relation);metadata.put("planOnly","true");if(intent==com.sobrenaturaldirector.decision.model.Intent.BOSS_ENCOUNTER||intent==com.sobrenaturaldirector.decision.model.Intent.HORROR_REVEAL)safety=ActionSafety.MAJOR;return new CandidateAction("plan:"+blueprint.getId(),intent,"NARRATIVE",blueprint.getBaseScore()/100.0,null,metadata,null,safety);}
    private static String fingerprint(NarrativePlanSynthesisRequest request,SituationBlueprint blueprint,String relation,Map<SemanticCapability,CapabilityDescriptor> selections){StringBuilder value=new StringBuilder(request.getSynthesisKey()).append('|').append(request.getIntent()).append('|').append(blueprint.fingerprint()).append('|').append(relation).append('|').append(request.isContinuation());for(Map.Entry<SemanticCapability,CapabilityDescriptor> e:selections.entrySet())value.append('|').append(e.getKey()).append('=').append(e.getValue().getProvider());return value.toString();}
    private static NarrativePlanSynthesisResult failure(NarrativePlanSynthesisRequest r,NarrativePlanSynthesisResult.Status status,SituationBlueprint b,String reason,List<String> attempts,int fallbacks,String relation,EnvironmentActionImpact impact){return new NarrativePlanSynthesisResult(status,r,b,null,b==null?Collections.<SemanticRole>emptyList():b.getRequiredRoles(),b==null?Collections.<SemanticRole>emptyList():b.getOptionalRoles(),Collections.<SemanticCapability,CapabilityDescriptor>emptyMap(),Collections.singletonList(reason),attempts,fallbacks,relation,impact,"");}
    private static NarrativePlanSynthesisResult invalid(){return new NarrativePlanSynthesisResult(NarrativePlanSynthesisResult.Status.INVALID_INPUT,null,null,null,Collections.<com.sobrenaturaldirector.situation.SemanticRole>emptyList(),Collections.<com.sobrenaturaldirector.situation.SemanticRole>emptyList(),Collections.<SemanticCapability,CapabilityDescriptor>emptyMap(),Collections.singletonList("NULL_REQUEST"),Collections.<String>emptyList(),0,"",null,"");}
}
