package com.sobrenaturaldirector.narrative;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import com.sobrenaturaldirector.domain.StableId;

/** Bounded semantic identity connecting plans without prescribing a story. */
public final class PersistentNarrativeThread {
    public static final int SCHEMA_VERSION=1, MAX_HISTORY=16, MAX_INTENTS=8;
    private final String id, subject, currentPlanId; private final NarrativeThreadState state;
    private final long createdTick,lastMeaningfulActivityTick,lastAssessmentTick;
    private final int dimension,regionX,regionZ; private final Set<String> tags; private final List<NarrativeThreadPlanHistory> history; private final List<String> recentIntents,reasons,situationIds;
    public PersistentNarrativeThread(String id,String subject,NarrativeThreadState state,long createdTick,long lastMeaningfulActivityTick,long lastAssessmentTick,int dimension,int regionX,int regionZ,Set<String> tags,String currentPlanId,List<NarrativeThreadPlanHistory> history,List<String> recentIntents,List<String> reasons){this(id,subject,state,createdTick,lastMeaningfulActivityTick,lastAssessmentTick,dimension,regionX,regionZ,tags,currentPlanId,history,recentIntents,reasons,Collections.<String>emptyList());}
    public PersistentNarrativeThread(String id,String subject,NarrativeThreadState state,long createdTick,long lastMeaningfulActivityTick,long lastAssessmentTick,int dimension,int regionX,int regionZ,Set<String> tags,String currentPlanId,List<NarrativeThreadPlanHistory> history,List<String> recentIntents,List<String> reasons,List<String> situationIds){this.id=StableId.require(id,"threadId");this.subject=text(subject);if(state==null)throw new IllegalArgumentException("state is required");this.state=state;this.createdTick=createdTick;this.lastMeaningfulActivityTick=lastMeaningfulActivityTick;this.lastAssessmentTick=lastAssessmentTick;this.dimension=dimension;this.regionX=regionX;this.regionZ=regionZ;TreeSet<String> sorted=new TreeSet<String>();if(tags!=null)sorted.addAll(tags);if(sorted.size()>16)throw new IllegalArgumentException("thread tag limit");this.tags=Collections.unmodifiableSet(sorted);this.currentPlanId=text(currentPlanId);this.history=boundedHistory(history);this.recentIntents=boundedTexts(recentIntents,MAX_INTENTS);this.reasons=boundedTexts(reasons,16);this.situationIds=boundedTexts(situationIds,32);}
    private static String text(String value){if(value==null)return"";if(value.length()>128)throw new IllegalArgumentException("thread text too long");return value;}
    private static List<NarrativeThreadPlanHistory> boundedHistory(List<NarrativeThreadPlanHistory> values){List<NarrativeThreadPlanHistory> out=new ArrayList<NarrativeThreadPlanHistory>(values==null?Collections.<NarrativeThreadPlanHistory>emptyList():values);if(out.size()>MAX_HISTORY)out=new ArrayList<NarrativeThreadPlanHistory>(out.subList(out.size()-MAX_HISTORY,out.size()));return Collections.unmodifiableList(out);}
    private static List<String> boundedTexts(List<String> values,int max){List<String> out=new ArrayList<String>(values==null?Collections.<String>emptyList():values);if(out.size()>max)out=new ArrayList<String>(out.subList(out.size()-max,out.size()));for(String value:out)text(value);return Collections.unmodifiableList(out);}
    public String getId(){return id;}public String getSubject(){return subject;}public NarrativeThreadState getState(){return state;}public long getCreatedTick(){return createdTick;}public long getLastMeaningfulActivityTick(){return lastMeaningfulActivityTick;}public long getLastAssessmentTick(){return lastAssessmentTick;}public int getDimension(){return dimension;}public int getRegionX(){return regionX;}public int getRegionZ(){return regionZ;}public Set<String> getTags(){return tags;}public String getCurrentPlanId(){return currentPlanId;}public List<NarrativeThreadPlanHistory> getHistory(){return history;}public List<String> getRecentIntents(){return recentIntents;}public List<String> getReasons(){return reasons;}public List<String> getSituationIds(){return situationIds;}
    public boolean isTerminal(){return state.isTerminal();}
    public PersistentNarrativeThread assess(NarrativeThreadState next,long tick,String reason){if(state.isTerminal()&&next!=state)throw new IllegalStateException("terminal thread cannot transition");List<String> rs=new ArrayList<String>(reasons);if(reason!=null&&!rs.contains(reason))rs.add(reason);return copy(next,lastMeaningfulActivityTick,tick,currentPlanId,history,recentIntents,rs,situationIds);}
    public PersistentNarrativeThread meaningfulActivity(long tick,String reason){List<String> rs=new ArrayList<String>(reasons);if(reason!=null&&!rs.contains(reason))rs.add(reason);return copy(state,tick,tick,currentPlanId,history,recentIntents,rs,situationIds);}
    public PersistentNarrativeThread attach(String planId,String intent,String blueprintId,long tick,String reason){List<NarrativeThreadPlanHistory> h=new ArrayList<NarrativeThreadPlanHistory>(history);h.add(new NarrativeThreadPlanHistory(planId,intent,blueprintId,tick,reason));List<String> intents=new ArrayList<String>(recentIntents);intents.add(intent);return copy(state,tick,lastAssessmentTick,planId,h,intents,reasons,situationIds);}
    public PersistentNarrativeThread linkSituation(String situationId,long tick,String reason){if(situationId==null||situationId.length()==0)return this;List<String> ids=new ArrayList<String>(situationIds);if(ids.contains(situationId))return this;ids.add(situationId);List<String> rs=new ArrayList<String>(reasons);if(reason!=null&&!rs.contains(reason))rs.add(reason);return copy(state,tick,tick,currentPlanId,history,recentIntents,rs,ids);}
    private PersistentNarrativeThread copy(NarrativeThreadState next,long meaningful,long assessed,String plan,List<NarrativeThreadPlanHistory> h,List<String> intents,List<String> rs,List<String> ids){return new PersistentNarrativeThread(id,subject,next,createdTick,meaningful,assessed,dimension,regionX,regionZ,tags,plan,h,intents,rs,ids);}
     public NBTTagCompound toNbt(){NBTTagCompound n=new NBTTagCompound();n.setInteger("schemaVersion",SCHEMA_VERSION);n.setString("id",id);n.setString("subject",subject);n.setString("state",state.name());n.setLong("createdTick",createdTick);n.setLong("lastMeaningfulActivityTick",lastMeaningfulActivityTick);n.setLong("lastAssessmentTick",lastAssessmentTick);n.setInteger("dimension",dimension);n.setInteger("regionX",regionX);n.setInteger("regionZ",regionZ);if(currentPlanId.length()>0)n.setString("currentPlanId",currentPlanId);NBTTagList tagsN=new NBTTagList();for(String value:tags){NBTTagCompound x=new NBTTagCompound();x.setString("value",value);tagsN.appendTag(x);}n.setTag("tags",tagsN);NBTTagList hist=new NBTTagList();for(NarrativeThreadPlanHistory value:history)hist.appendTag(value.toNbt());n.setTag("history",hist);NBTTagList ints=new NBTTagList();for(String value:recentIntents){NBTTagCompound x=new NBTTagCompound();x.setString("value",value);ints.appendTag(x);}n.setTag("recentIntents",ints);NBTTagList rs=new NBTTagList();for(String value:reasons){NBTTagCompound x=new NBTTagCompound();x.setString("value",value);rs.appendTag(x);}n.setTag("reasons",rs);NBTTagList situations=new NBTTagList();for(String value:situationIds){NBTTagCompound x=new NBTTagCompound();x.setString("value",value);situations.appendTag(x);}n.setTag("situationIds",situations);return n;}
     public static PersistentNarrativeThread fromNbt(NBTTagCompound n){if(n==null||n.getInteger("schemaVersion")!=SCHEMA_VERSION)throw new IllegalArgumentException("invalid thread schema");Set<String> tags=new TreeSet<String>();NBTTagList ts=n.getTagList("tags",10);for(int i=0;i<ts.tagCount();i++)tags.add(ts.getCompoundTagAt(i).getString("value"));List<NarrativeThreadPlanHistory> h=new ArrayList<NarrativeThreadPlanHistory>();NBTTagList hs=n.getTagList("history",10);for(int i=0;i<hs.tagCount();i++)h.add(NarrativeThreadPlanHistory.fromNbt(hs.getCompoundTagAt(i)));return new PersistentNarrativeThread(n.getString("id"),n.getString("subject"),NarrativeThreadState.valueOf(n.getString("state")),n.getLong("createdTick"),n.getLong("lastMeaningfulActivityTick"),n.getLong("lastAssessmentTick"),n.getInteger("dimension"),n.getInteger("regionX"),n.getInteger("regionZ"),tags,n.getString("currentPlanId"),h,strings(n.getTagList("recentIntents",10)),strings(n.getTagList("reasons",10)),strings(n.getTagList("situationIds",10)));}
    private static List<String> strings(NBTTagList list){List<String> out=new ArrayList<String>();for(int i=0;i<list.tagCount();i++)out.add(list.getCompoundTagAt(i).getString("value"));return out;}
}
