package com.sobrenaturaldirector.planner;
import java.nio.charset.Charset;import java.security.MessageDigest;import java.security.NoSuchAlgorithmException;import java.util.*;
import com.sobrenaturaldirector.decision.model.Intent;import com.sobrenaturaldirector.planner.model.*;import com.sobrenaturaldirector.planner.requirement.PlanRequirement;import com.sobrenaturaldirector.planner.trace.PlanningTrace;import com.sobrenaturaldirector.planner.validation.PlanValidator;
/** Pure template-assisted planner. It produces hypotheses, never execution. */
public final class DirectorPlanner {public static final int MAX_ALTERNATIVES=3,MAX_REPLANS=2;
 public PlanningResult plan(PlanningContext c){Intent intent=c.getDecision().getSelected().getIntent();String source=c.getDecision().getTrace().getSelectedId();if(intent==Intent.NO_ACTION)return result(PlanningResultStatus.NO_PLAN_REQUIRED,null,new PlanningTrace("request:"+source,source,intent,"NONE","NO_PLAN_REQUIRED",Collections.<String>emptyList(),Collections.<String>emptyList(),Collections.<String>emptyList()));List<PlanRequirement> req=new ArrayList<PlanRequirement>();List<PlanStep>steps=new ArrayList<PlanStep>();Map<String,Double>cost=new TreeMap<String,Double>();String blueprint;
   if(intent==Intent.AMBIENT_HINT){blueprint="AMBIENT_HINT";steps.add(step("hint",PlanStepType.REVEAL,null,null));}
   else if(intent==Intent.MINOR_ENCOUNTER){blueprint="MINOR_ENCOUNTER";req.add(require(c,"CONTENT_ROLE:COMMON_HOSTILE",false));steps.add(step("content",PlanStepType.PREPARE_CONTENT,null,ids(req)));steps.add(step("encounter",PlanStepType.PREPARE_ENCOUNTER,"content",ids(req)));steps.add(step("activate",PlanStepType.ACTIVATE,"encounter",null));cost.put("threat",1.0);}
   else if(intent==Intent.RECOVERY){blueprint="RECOVERY";steps.add(step("recovery",PlanStepType.WAIT_FOR_REVEAL,null,null));}
   else {blueprint=structureBlueprint(intent);req.add(require(c,"LOCATION:UNDERGROUND",false));req.add(require(c,"STRUCTURE_THEME:CEMETERY",true));req.add(require(c,"STRUCTURE_TYPE:CATACOMB",false));req.add(require(c,"CONTENT_ROLE:COMMON_HOSTILE",false));req.add(require(c,"CONTENT_ROLE:BOSS",intent==Intent.MYSTERY_SETUP));req.add(require(c,"CONTENT_ROLE:HIGH_VALUE_REWARD",intent==Intent.MYSTERY_SETUP));req.add(new PlanRequirement("safety","SAFETY:AVOID_PLAYER_BUILD",c.isSafetyKnown()?RequirementStatus.SATISFIED:RequirementStatus.DEFERRED,false,null));
     steps.add(step("location",PlanStepType.SELECT_LOCATION,null,Collections.singletonList("LOCATION:UNDERGROUND")));steps.add(step("validate",PlanStepType.VALIDATE_LOCATION,"location",Collections.singletonList("safety")));steps.add(step("reserve",PlanStepType.REQUEST_REGION_RESERVATION,"validate",null));steps.add(step("structure",PlanStepType.PREPARE_STRUCTURE,"reserve",Collections.singletonList("STRUCTURE_TYPE:CATACOMB")));steps.add(step("population",PlanStepType.PREPARE_CONTENT,"structure",Collections.singletonList("CONTENT_ROLE:COMMON_HOSTILE")));if(intent==Intent.BOSS_ENCOUNTER||intent==Intent.BOSS_SETUP){steps.add(step("arena",PlanStepType.PREPARE_ENCOUNTER,"structure",Collections.singletonList("CONTENT_ROLE:BOSS")));steps.add(step("boss",PlanStepType.PREPARE_BOSS,"arena",Collections.singletonList("CONTENT_ROLE:BOSS")));steps.add(step("reward",PlanStepType.PREPARE_REWARD,"boss",Collections.singletonList("CONTENT_ROLE:HIGH_VALUE_REWARD")));}steps.add(step("hide",PlanStepType.HIDE,steps.get(steps.size()-1).getStepId(),null));steps.add(step("wait",PlanStepType.WAIT_FOR_REVEAL,"hide",null));steps.add(step("reveal",PlanStepType.REVEAL,"wait",null));steps.add(step("activate",PlanStepType.ACTIVATE,"reveal",null));steps.add(step("cleanup",PlanStepType.CLEANUP,"activate",null));cost.put("threat",intent==Intent.BOSS_ENCOUNTER?5.0:2.0);cost.put("structure",3.0);}
   List<String>reasons=new ArrayList<String>();for(PlanRequirement r:req)if(r.getStatus()!=RequirementStatus.SATISFIED&&!r.isOptional())reasons.add("REQUIREMENT_"+r.getStatus().name()+":"+r.getId());for(Map.Entry<String,Double>e:cost.entrySet())if(c.getBudgets().get(e.getKey())==null||c.getBudgets().get(e.getKey())<e.getValue())reasons.add("BUDGET_INSUFFICIENT:"+e.getKey());DirectorPlan plan=new DirectorPlan(id(source,intent,c.getReferenceTick()),source,intent,goal(intent),horizon(intent),reasons.isEmpty()?PlanStatus.TENTATIVE:PlanStatus.SUSPENDED,steps,req,cost,c.getDecision().getTrace().getContextFingerprint(),"SAME_THEME_OR_DEFER","BOUNDED_REPLAN");if(!new PlanValidator().validate(plan).isValid())return result(PlanningResultStatus.UNPLANNABLE,plan,trace(source,intent,blueprint,req,steps,reasons,"UNPLANNABLE"));return result(reasons.isEmpty()?PlanningResultStatus.SUCCESS:PlanningResultStatus.DEFERRED,plan,trace(source,intent,blueprint,req,steps,reasons,reasons.isEmpty()?"SUCCESS":"DEFERRED"));}
 private PlanRequirement require(PlanningContext c,String type,boolean optional){Boolean v=c.getCapabilities().get(type);return new PlanRequirement(type.toLowerCase().replace(':','_'),type,v==null?RequirementStatus.DEFERRED:(v?RequirementStatus.SATISFIED:RequirementStatus.UNSATISFIED),optional,Collections.<String>emptyList());}
 private static PlanStep step(String id,PlanStepType type,String dep,List<String>req){return new PlanStep("step:"+id,type,dep==null?null:Collections.singletonList(dep.startsWith("step:")?dep:"step:"+dep),req,null,Collections.<String,Double>emptyMap(),"DEFER_OR_REPLAN",false);}
 private static String structureBlueprint(Intent i){return i==Intent.BOSS_ENCOUNTER||i==Intent.BOSS_SETUP?"BOSS_ENCOUNTER":i==Intent.STRUCTURE_SEED||i==Intent.STRUCTURE_REVEAL?"STRUCTURE_DISCOVERY":"MAJOR_DISCOVERY";}private static String goal(Intent i){return i.name()+"_ABSTRACT_GOAL";}private static PlanHorizon horizon(Intent i){return i==Intent.AMBIENT_HINT||i==Intent.MINOR_ENCOUNTER||i==Intent.RECOVERY?PlanHorizon.SHORT:PlanHorizon.MEDIUM;}private static String id(String source,Intent i,long tick){try{byte[]b=MessageDigest.getInstance("SHA-256").digest((source+":"+i+":"+tick).getBytes(Charset.forName("UTF-8")));StringBuilder s=new StringBuilder("plan:");for(int x=0;x<8;x++)s.append(String.format("%02x",b[x]&255));return s.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private static PlanningTrace trace(String source,Intent i,String b,List<PlanRequirement>r,List<PlanStep>s,List<String>why,String result){List<String>a=new ArrayList<String>(),z=new ArrayList<String>();for(PlanRequirement x:r)a.add(x.getId()+":"+x.getStatus());for(PlanStep x:s)z.add(x.getStepId());return new PlanningTrace("request:"+source,source,i,b,result,a,z,why);}private static PlanningResult result(PlanningResultStatus status,DirectorPlan p,PlanningTrace t){return new PlanningResult(status,p,t);}private static List<String>ids(List<PlanRequirement>r){List<String>x=new ArrayList<String>();for(PlanRequirement q:r)x.add(q.getId());return x;}
}
