import sys
from pathlib import Path

p=Path(sys.argv[1] if len(sys.argv)>1 else 'runtime-tests/server/public-shadow-runtime-closure.properties')
v={}
for line in p.read_text(encoding='utf-8').splitlines():
    if '=' in line: k,x=line.split('=',1); v[k]=x
required='MODEL_LOADER MODEL_HASH_GUARD MODEL_CONFIG_GUARD MODEL_SCHEMA_GUARD MODEL_WEIGHT_VALIDATION MODEL_READY_ON_DEDICATED_BOOT MODEL_FAILURE_FAILSAFE SHADOW_SERVICE_ENABLED CONSENT_SERVICE CONSENT_REQUIRED SESSION_SCOPED_CONSENT NO_PRECONSENT_RESEARCH_RECORDS OPAQUE_PARTICIPANT_ID MULTIPLAYER_ISOLATION CROSS_PARTICIPANT_CONTAMINATION IMMUTABLE_SNAPSHOT ASYNC_SCORING ASYNC_WORLD_ACCESS DECISION_WAIT_ON_SHADOW JSONL_COLLECTION ACTUAL_DECISION_COLLECTION SHADOW_SCORE_COLLECTION OUTCOME_TRACKING OUTCOME_JOIN OUTCOME_TTL BOUNDED_QUEUE DISK_ROTATION DISK_BUDGET HARNESS_E2E HARNESS_DECISIONS HARNESS_CANONICAL_RECORDS TWO_PLAYER_TEST COLD_RESTART DEDICATED_SERVER_BOOT GRACEFUL_SHUTDOWN JAVA_TESTS JAVA_TEST_COUNT PYTHON_TESTS PYTHON_TEST_COUNT JAR_CLASS_MAJOR PROTECTED_WORLD_TOUCHED ORIGINAL_MODS_MODIFIED SECRETS_COMMITTED FULL_REAL_EXPERIENCE_TRAINING MODEL_WEIGHTS_CHANGED FINAL_GATE'.split()
bad=[k for k in required if not v.get(k)]
expected={'MODEL_LOADER':'PASS','MODEL_HASH_GUARD':'PASS','MODEL_CONFIG_GUARD':'PASS','MODEL_SCHEMA_GUARD':'PASS','MODEL_WEIGHT_VALIDATION':'PASS','MODEL_READY_ON_DEDICATED_BOOT':'PASS','SHADOW_SERVICE_ENABLED':'YES','CONSENT_REQUIRED':'YES','SESSION_SCOPED_CONSENT':'YES','NO_PRECONSENT_RESEARCH_RECORDS':'PASS','OPAQUE_PARTICIPANT_ID':'PASS','ASYNC_WORLD_ACCESS':'0','DECISION_WAIT_ON_SHADOW':'NO','CROSS_PARTICIPANT_CONTAMINATION':'0','TRAINING_ALLOWED_DEFAULT':'NO','AUTOMATIC_REWARD_LABELING':'NO','PROTECTED_WORLD_TOUCHED':'NO','ORIGINAL_MODS_MODIFIED':'NO','SECRETS_COMMITTED':'NO','FULL_REAL_EXPERIENCE_TRAINING':'NO','MODEL_WEIGHTS_CHANGED':'NO','JAR_CLASS_MAJOR':'52','FINAL_GATE':'PASS'}
bad += [k for k,x in expected.items() if v.get(k)!=x]
for k in ('HARNESS_DECISIONS','HARNESS_CANONICAL_RECORDS','JAVA_TEST_COUNT','PYTHON_TEST_COUNT'):
    try:
        if int(v.get(k,'0'))<=0: bad.append(k)
    except ValueError: bad.append(k)
if bad: print('closure gate failed: '+','.join(sorted(set(bad)))); sys.exit(1)
print('public shadow runtime closure gate PASS; external ingress remains manual')
