import sys
from pathlib import Path

keys="RUN_ID SOURCE_COMMIT FEATURE_SCHEMA DATASET_REVALIDATION V2_LEAKAGE_FREE V2_DETERMINISM SPLIT_LEAKAGE TRAIN_ONLY_NORMALIZATION_FIT TRAIN_ONLY_VOCAB_FIT TRAIN_ROWS VALIDATION_ROWS TEST_ROWS HOLDOUT_ROWS TEST_USED_FOR_TRAINING TEST_USED_FOR_TUNING HOLDOUT_USED_FOR_TRAINING HOLDOUT_USED_FOR_TUNING GPU_DOCTOR CUDA GPU_COUNT GPU_BENCHMARK_COMPLETED FULL_TRAIN_DEVICE TUNING_COMPLETED MODEL_FREEZE MODEL_FREEZE_CONFIG_SHA256 MODEL_FREEZE_COMMIT FINAL_TRAIN TEST_EVALUATION POST_TEST_MODEL_CHANGES HOLDOUT_EVALUATION POST_HOLDOUT_MODEL_CHANGES CHECKPOINT_LATEST CHECKPOINT_BEST CHECKPOINT_SYNC CHECKPOINT_SHA_MATCH RESUME_COMPATIBILITY PYTHON_TESTS JAVA_REGRESSION GIT_DIFF_CHECK PRODUCTION_RUNTIME_BEHAVIOR_CHANGED PROTECTED_WORLD_TOUCHED SECRETS_COMMITTED SHADOW_MODE_READINESS FINAL_GATE".split()
p=Path(sys.argv[1] if len(sys.argv)>1 else "runtime-tests/benchmark/learned-scorer-v1-full-evaluation.properties")
v={}
for line in p.read_text().splitlines():
    if "=" in line: k,x=line.split("=",1); v[k]=x
bad=[k for k in keys if not v.get(k) or v[k] in ("NOT_RUN","PARTIAL") or v[k].startswith("FAIL")]
if bad or v.get("FINAL_GATE")!="PASS": print("gate failed: "+",".join(bad or ["FINAL_GATE"])); sys.exit(1)
print("gate PASS")
