import sys
from pathlib import Path

required="RUN_ID SOURCE_COMMIT DATASET_VERSION FEATURE_SCHEMA FEATURE_SCHEMA_SHA256 GENERATION_SPEC_SHA256 TARGET_PROVENANCE SYNTHETIC_SUPERVISION REAL_GAMEPLAY_OUTCOME_SUPERVISION GENERATION_SPEC_FREEZE PILOT_SMALL PILOT_MEDIUM DETERMINISM TOTAL_STATE_GROUPS TOTAL_CANDIDATE_ROWS TRAIN_STATE_GROUPS VALIDATION_STATE_GROUPS TEST_STATE_GROUPS HOLDOUT_STATE_GROUPS TRAIN_ROWS VALIDATION_ROWS TEST_ROWS HOLDOUT_ROWS SEQUENCE_EPISODES SEQUENCE_STATES CROSS_SPLIT_STATE_INPUT_DUPLICATES CROSS_SPLIT_CANDIDATE_INPUT_DUPLICATES TARGET_CONFLICTS LEAKAGE_AUDIT TARGET_NOT_IN_INPUTS POST_DECISION_INPUTS ID_FEATURE_LEAKAGE SPLIT_LEAKAGE TRAINING_ALLOWED_POLICY TEST_USED_FOR_TUNING HOLDOUT_USED_FOR_TUNING FEATURE_COVERAGE CANDIDATE_SET_COVERAGE NO_ACTION_COVERAGE PROVIDER_CAPABILITY_COVERAGE STREAMING_GENERATION SHARDING MANIFEST SHARD_HASHES PEAK_RSS_OK OOM_COUNT V3_DATASET_LOAD V3_GPU_FORWARD V3_GPU_BACKWARD V3_CHECKPOINT_SMOKE KAGGLE_COPY KAGGLE_SHA_MATCH PYTHON_TESTS JAVA_TESTS GIT_DIFF_CHECK PRODUCTION_RUNTIME_BEHAVIOR_CHANGED BENCHMARK_CLASSES_IN_PRODUCTION_JAR PROTECTED_WORLD_TOUCHED SECRETS_COMMITTED ORIGINAL_MODS_MODIFIED FULL_V3_TRAINING_PERFORMED SHADOW_MODE_ENABLED FINAL_GATE".split()
p=Path(sys.argv[1] if len(sys.argv)>1 else "runtime-tests/benchmark/director-experience-v3-foundation.properties")
values={}
for line in p.read_text().splitlines():
    if "=" in line: k,v=line.split("=",1); values[k]=v
bad=[k for k in required if not values.get(k) or values[k] in ("NOT_RUN","PARTIAL") or values[k].startswith("FAIL")]
if int(values.get("TOTAL_STATE_GROUPS","0"))<50000 or int(values.get("TOTAL_CANDIDATE_ROWS","0"))<250000: bad.append("scale")
if any(values.get(k)!="0" for k in ("CROSS_SPLIT_STATE_INPUT_DUPLICATES","CROSS_SPLIT_CANDIDATE_INPUT_DUPLICATES","TARGET_CONFLICTS","POST_DECISION_INPUTS")): bad.append("leakage_counts")
if bad or values.get("FINAL_GATE")!="PASS": print("gate failed: "+",".join(bad or ["FINAL_GATE"])); sys.exit(1)
print("gate PASS")
