import sys
from pathlib import Path

required = """RUN_ID SOURCE_COMMIT V4_MODEL_EXPORT_SHA256 V4_CHECKPOINT_REFERENCE_SHA256 V4_FROZEN_CONFIG_SHA256 FEATURE_SCHEMA_SHA256 SHADOW_SCHEMA SHADOW_SCHEMA_VERSION DEFAULT_SHADOW_ENABLED OBSERVATION_PIPELINE_READINESS LEARNED_CONTROL_READINESS SHADOW_INFLUENCES_DECISION SHADOW_INFLUENCES_EXECUTION SHADOW_INFLUENCES_SAFETY IMMUTABLE_SNAPSHOT ASYNC_SCORING ASYNC_WORLD_ACCESS BOUNDED_QUEUE QUEUE_OVERFLOW_FAILSAFE MODEL_LOAD MODEL_HASH_GUARD MODEL_SCHEMA_GUARD MODEL_FAILURE_FAILSAFE COLLECTOR ASYNC_WRITER SEGMENT_ROTATION DISK_BUDGET COLLECTOR_FAILURE_FAILSAFE PRIVACY_MINIMIZATION NETWORK_TELEMETRY DECISION_SEQUENCE_MATCH EXECUTION_SIDE_EFFECT_SEMANTIC_MATCH DEFAULT_BEHAVIOR_MATCH SLOW_SCORER_NON_BLOCKING NO_ACTION_COLLECTION OUTCOME_TRACKING OUTCOME_TTL INCOMPLETE_OUTCOME_HANDLING AUTOMATIC_REWARD_LABELING SESSION_MANIFEST COLD_RESTART WORKER_LEAKS RUNTIME_FEATURE_PARITY JAVA_MODEL_PARITY HARNESS_PIPELINE_E2E HARNESS_EXPERIENCE_RECORDS REAL_EXPERIENCE_STAGING_BUILDER TRAINING_ALLOWED_DEFAULT MODEL_WEIGHTS_CHANGED FULL_REAL_EXPERIENCE_TRAINING_PERFORMED JAVA_TESTS JAVA_TEST_COUNT PYTHON_TESTS PYTHON_TEST_COUNT GIT_DIFF_CHECK JAR_BUILD JAR_CLASS_MAJOR JAR_SHA256 JAR_CHANGED PRODUCTION_CODE_CHANGED DEFAULT_GAMEPLAY_DECISION_BEHAVIOR_CHANGED HARD_SAFETY_CHANGED PROTECTED_WORLD_TOUCHED ORIGINAL_MODS_MODIFIED SECRETS_COMMITTED SHADOW_MODE_CONTROL_ENABLED ADVISORY_MODE_ENABLED LEARNED_CONTROL_ENABLED RELEASE_FINAL_DECLARED FINAL_GATE""".split()
path = Path(sys.argv[1] if len(sys.argv) > 1 else "runtime-tests/shadow/shadow-runtime-experience-foundation.properties")
values = {}
for line in path.read_text(encoding="utf-8").splitlines():
    if "=" in line:
        key, value = line.split("=", 1); values[key] = value
bad = [key for key in required if key not in values or not values[key] or values[key] in ("NOT_RUN", "PARTIAL")]
expected = {"DEFAULT_SHADOW_ENABLED":"NO", "OBSERVATION_PIPELINE_READINESS":"PASS", "LEARNED_CONTROL_READINESS":"INSUFFICIENT_EVIDENCE", "SHADOW_INFLUENCES_DECISION":"NO", "SHADOW_INFLUENCES_EXECUTION":"NO", "SHADOW_INFLUENCES_SAFETY":"NO", "ASYNC_WORLD_ACCESS":"0", "DECISION_SEQUENCE_MATCH":"100%", "WORKER_LEAKS":"0", "AUTOMATIC_REWARD_LABELING":"NO", "TRAINING_ALLOWED_DEFAULT":"NO", "MODEL_WEIGHTS_CHANGED":"NO", "FULL_REAL_EXPERIENCE_TRAINING_PERFORMED":"NO", "JAR_CLASS_MAJOR":"52", "DEFAULT_GAMEPLAY_DECISION_BEHAVIOR_CHANGED":"NO", "HARD_SAFETY_CHANGED":"NO", "PROTECTED_WORLD_TOUCHED":"NO", "ORIGINAL_MODS_MODIFIED":"NO", "SECRETS_COMMITTED":"NO", "SHADOW_MODE_CONTROL_ENABLED":"NO", "ADVISORY_MODE_ENABLED":"NO", "LEARNED_CONTROL_ENABLED":"NO", "RELEASE_FINAL_DECLARED":"NO", "FINAL_GATE":"PASS"}
bad += [key for key, value in expected.items() if values.get(key) != value]
try:
    if int(values.get("HARNESS_EXPERIENCE_RECORDS", "0")) <= 0: bad.append("HARNESS_EXPERIENCE_RECORDS")
    if int(values.get("JAVA_TEST_COUNT", "0")) < 300: bad.append("JAVA_TEST_COUNT")
    if int(values.get("PYTHON_TEST_COUNT", "0")) < 10: bad.append("PYTHON_TEST_COUNT")
except ValueError: bad.append("counts")
if bad: print("gate failed: " + ",".join(sorted(set(bad)))); sys.exit(1)
print("shadow foundation gate PASS")
