package com.sobrenaturaldirector.decision;
import java.nio.charset.Charset; import java.security.MessageDigest; import java.security.NoSuchAlgorithmException; import java.util.*;
import com.sobrenaturaldirector.decision.candidate.CandidateGenerator; import com.sobrenaturaldirector.decision.constraint.*; import com.sobrenaturaldirector.decision.model.*; import com.sobrenaturaldirector.decision.random.DeterministicRng; import com.sobrenaturaldirector.decision.trace.*; import com.sobrenaturaldirector.decision.utility.*; import com.sobrenaturaldirector.shadow.*;
public final class DecisionEngine {
    public static final int DECISION_MODEL_VERSION=1; private final CandidateGenerator generator=new CandidateGenerator(); private final UtilityEvaluator evaluator=new UtilityEvaluator(); private final ShadowObservationService shadow;
    public DecisionEngine(){this(null);} public DecisionEngine(ShadowObservationService shadow){this.shadow=shadow;}
    public DecisionResult decide(DecisionContext context,long directorSeed){if(context==null)throw new IllegalArgumentException("INVALID_CONTEXT");return decide(context,generator.generate(context),directorSeed);}
    public DecisionResult decide(DecisionContext context,List<CandidateAction> input,long directorSeed){if(context==null||input==null)throw new IllegalArgumentException("INVALID_CONTEXT"); if(input.size()>CandidateGenerator.MAX_CANDIDATES)throw new IllegalArgumentException("CANDIDATE_LIMIT_EXCEEDED"); List<CandidateAction> candidates=new ArrayList<CandidateAction>(input); Collections.sort(candidates,new Comparator<CandidateAction>(){public int compare(CandidateAction a,CandidateAction b){return a.getCandidateId().compareTo(b.getCandidateId());}}); Set<String> ids=new HashSet<String>(); for(CandidateAction a:candidates)if(!ids.add(a.getCandidateId()))throw new IllegalArgumentException("DUPLICATE_CANDIDATE_ID");
        List<List<ConstraintResult>> allConstraints=new ArrayList<List<ConstraintResult>>(); List<UtilityScoreBreakdown> scores=new ArrayList<UtilityScoreBreakdown>(); List<Integer> eligible=new ArrayList<Integer>();
        for(int i=0;i<candidates.size();i++){CandidateAction a=candidates.get(i);List<ConstraintResult> cr=StandardConstraints.evaluate(context,a);allConstraints.add(cr);boolean ok=true;for(ConstraintResult x:cr)if(!x.isPassed())ok=false;UtilityScoreBreakdown score=evaluator.evaluate(context,a);scores.add(score);if(ok)eligible.add(i);}
        if(eligible.isEmpty()){for(int i=0;i<candidates.size();i++)if(candidates.get(i).getIntent()==Intent.NO_ACTION)eligible.add(i);if(eligible.isEmpty())throw new IllegalStateException("NO_VALID_NO_ACTION");}
        double best=Double.NEGATIVE_INFINITY;for(Integer i:eligible)best=Math.max(best,scores.get(i).getFinalScore());List<Integer> ties=new ArrayList<Integer>();for(Integer i:eligible)if(Double.compare(scores.get(i).getFinalScore(),best)==0)ties.add(i);DeterministicRng rng=DeterministicRng.stream(directorSeed,"decision",Long.toString(context.getTick()));int chosen=ties.get(ties.size()==1?0:rng.nextInt(ties.size()));
        List<CandidateTrace> traces=new ArrayList<CandidateTrace>();for(int i=0;i<candidates.size();i++)traces.add(new CandidateTrace(candidates.get(i).getCandidateId(),eligible.contains(i),i==chosen,allConstraints.get(i),scores.get(i)));CandidateAction selected=candidates.get(chosen);DecisionTrace decisionTrace=new DecisionTrace(context.getTick(),rng.getSeed(),fingerprint(context),traces,selected.getIntent(),selected.getCandidateId());DecisionResult result=new DecisionResult(selected,decisionTrace);if(shadow!=null&&!eligible.isEmpty())try{List<CandidateAction> eligibleCandidates=new ArrayList<CandidateAction>();for(Integer i:eligible)eligibleCandidates.add(candidates.get(i));shadow.submit(ShadowSnapshotFactory.create(context,eligibleCandidates,selected.getCandidateId(),context.getTick(),decisionTrace.getContextFingerprint()));}catch(RuntimeException ignored){}return result;
    }
    private static String fingerprint(DecisionContext c){try{MessageDigest d=MessageDigest.getInstance("SHA-256");String s=c.getTick()+":"+c.getWorldAge()+":"+c.getTension()+":"+c.getPressure()+":"+c.getFatigue()+":"+c.getRecoveryNeed()+":"+c.getHealthRatio()+":"+c.getCombatPower()+":"+c.getIsolation()+":"+c.isUnderground()+":"+c.isObservingSite();byte[] b=d.digest(s.getBytes(Charset.forName("UTF-8")));StringBuilder x=new StringBuilder();for(int i=0;i<8;i++)x.append(String.format("%02x",b[i]&255));return x.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
